### ISSUE TITLE
Buck frequently goes over cache dir_max_size

### ISSUE THREAD

**Issue by mikekap** [facebook/buck#1000]
We're running a buck server with `serve_local_cache=true`. We have `dir_max_size=90G`, but quite frequently the server goes over 90G of space usage (the underlying drive is ~120G, so we get out of disk errors).

We "start" the server via
```
#!/bin/bash
set -e

while true
do
  sleep 10
  buck server status --http-port
done
```

I noticed that the daemon occasionally restarts which means the cache directory might not be cleaned. Might it be worth adding a directory clean at buckd startup?

**Comment by sdwilsh** [comment]
> I noticed that the daemon occasionally restarts which means the cache
> directory might not be cleaned. Might it be worth adding a directory
> clean at buckd startup?
That could lead to a bad experience if we have to cleanup a lot.  But I 
guess we already have that risk with commands contending for the single 
daemon.

**Comment by yiding** [comment]
The currently logic will clean after you write 'dir_max_size / 2` bytes. Obviously this will reset when buck is restarted. Cleaning is also very slow due to the dir cache basically storing files naively on the file system without any form of index, so it will traverse all the files to get a sense of what's there, then delete the the oldest entries. 

* In the short term an option to clean-on-startup, or a dedicated command to clean dir cache, is useful. 
* In the long term we probably want to re-think the implementation of the directory cache such that cleaning is not a slow monolithic operation.
