### ISSUE TITLE
Support test results to be cached

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#1011]
Currently, the test results cache is only local. This forces a full rerun of the test suite when run on CI because none of the results are available in the network cache.

I understand it can be a problem if one has flaky tests or tests that use environment variables to have this behavior, but in the absence of that, it would be great to have this as an option.

**Comment by dreiss** [comment]
Gautam and I discussed this on Slack.  For context, we considered implementing this a while back, but decided not to because we (Facebook) don't want to use it.  That said, I think we'd be open to a PR for this, as long as it's possible to disable.

I foresee two likely sticking points:

- The test running phase is currently pretty different from the building phase, but this is a fairly superficial problem.
- It's not clear how the cache should work in the presence of test filters.  This is probably mostly a user-expectation problem.

**Comment by kageiit** [comment]
@dreiss where should we start looking to make changes for this option? Any pointers would be helpful

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
