### ISSUE TITLE
prebuilt_cxx_library_group butchers trailing version numbers of shared library names

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#1045]
Buck unfortunately constructs the wrong ld command if a shared-library has a version number in the end. For some reason it strips the leading number from the library name.

BUCK-file:
```
prebuilt_cxx_library_group(
  name = 'clang-libs',
  shared_link = ['$(rel-lib libclang.so.4.0)'],
  shared_libs = { 'libclang.so.4.0' : 'libs/libclang.so.4.0' }
#or   shared_libs = { 'libclang.so' : 'libs/libclang.so.4.0' }
)
```
produces following error message:
```
/usr/bin/ld: cannot find -lclang.so.4
collect2: error: ld returned 1 exit status

BUILD FAILED: //:clang#default,shared failed with exit code 1:
c++ link
stderr: /usr/bin/ld: cannot find -lclang.so.4
collect2: error: ld returned 1 exit status
```

**Comment by aiked** [comment]
@andrewjcg could you take a look at this?

**Comment by andrewjcg** [comment]
Yeah, the `rel-libs` macro is really only meant for libraries which don't contain SONAMEs and so need to be linked in a special way.  In those few cases I've seen, the libraries usually have the `lib<name>.so`, which the `rel-lib` support converts to `-L<prefix> -l<name>` which the link will then use to look for `lib<name>.so`.  I think this thing breaks down in the presence of version suffices, as even if we do strip the version suffix of correctly when forming the link line, the linker won't then know how to reconstruct the shared lib path.  However, it's common for devel installations to include a symlink from `lib<name>.so` to `lib<name>.so.<version>`, in which case I think the symlink can be used in place of the versioned name throughout (e.g. use `libclang.so` instead of `libclang.so.4.0` in all locations in your BUCK file).

All that said, I think clang normally builds it's shared libs *with* a SONAME, so I would think you should be able to just use `$(lib libclang.so.4.0)` and have everything work correctly.  Was there something not working with that approach which made you start using `$(rel-lib ...)`?

**Comment by nikhedonia** [comment]
> Was there something not working with that approach which made you start using $(rel-lib ...)?
`$(lib)` expresses the same issue and additionally requires me to set the `-rpath` manually.

I use the libs as deps for another shared library and link this library to an executable.
I discovered that copying the library with the trailing version numbers into the buck-out folder and
setting `link_style='shared'` on the executable solves the problem.

It surprises me that link_style makes a difference here as i only have shared libraries in my setup and linking shared libraries statically does not really make sense.

**Comment by v-jizhang** [comment]
Sorry we haven't update this issue for more than 3 years. At this point, we are closing this because it is quite out of date and it is not clear if the issue still exists. Please create a new one if you still see the problem. Thank you.
