### ISSUE TITLE
How to convert iOS project to buck project？

### ISSUE THREAD

**Issue by SwiftlyFly** [facebook/buck#1075]
Now，i have a iOS project,  if i want to convert it to a buck project,  should i creat a BUCK file for every directory manually？ or it can do it automatically？

**Comment by ttsugriy** [comment]
AFAIK there is no tool to perform this migration automatically and such tool might not be easy to implement, since buck projects include much more information than Xcode project - everything is very explicit (dependencies, outputs, etc), so going from Buck to almost anything else is mostly straightforward, but not the other way around. So, I'm afraid you'll need to create required BUCK files manually.
