### ISSUE TITLE
RFC: Introduce build rules for building GWT applications.

### ISSUE THREAD

**Issue by bolinfest** [facebook/buck#109]
I'm looking into adding build rules for building GWT applications. I'm curious what folks think the arguments to the rules should look like.

* Do we need a special `gwt_library()` rule, or can we just use `java_library()`? My intuition is that if you use JSNI in your Java code, then you need to classify that as a `gwt_library()`.
* How do you deal with dependencies that have dual implementations: one for the JRE and one for JavaScript? For example, you may have a subgraph of dependencies that transitively depend on Guava. Then at the top, you have a `gwt_binary()` target and a `java_binary()` target? How do you ensure that the `gwt_binary()` pulls in `guava-gwt-17.0.jar` while the `java_binary()` pulls in `guava-17.0.jar`? One option is to have parallel versions of each subgraph, but that seems messy.
* How can we design `gwt_binary()` (or this whole system of rules) so that it is easy to run the GWT app in developer mode? Ideally, a developer should not have to run `buck build` after every code modification in order to reload the GWT app. The existing edit-refresh-test cycle needs to be preserved.

**Comment by davido** [comment]
I've spent some time to understand why small extension to  Gerrit GWT Plugin API worked as expected in standalone build mode, but failed to compile in Gerrit tree mode: [1]. Classpath of GWT compiler invocation was polluted with dozens of pseudo GWT modules, that interfered with this new extension. 

What happened? The easiest way to see the problem is to check the source code: [2].

It turns out (it wasn't really clear to me) that the implementation reconstructs GWT modules from the dependency graph. In Gerrit tree build `//gerrit-plugin-api:lib` that was passed here, resolved to dozens of rules and thus the whole Gerrit server stuff was included as GWT modules and passed to the GWT compiler. Even though we used provided deps.

In standalone mode, that makes use of `bucklets`, the implementation is different: `plugin-api.jar` is fetched from Central and is used as module deps. Dependency graph here is empty, so nothing is passed in addition to GWT compiler and the classpath wasn't polluted.

I think that the reachability resolution algorithm should differentiate between provided deps and normal deps. Another option to consider is to make dependency module resolution configurable.

[1] https://gerrit-review.googlesource.com/#/c/63489
[2] https://github.com/facebook/buck/blob/master/src/com/facebook/buck/gwt/GwtBinaryDescription.java#L115,L138

**Comment by Coneko** [comment]
@davido: I've opened a new issue for that: #239

I think this one can be closed now that GWT rules are in.

**Comment by BruceZu** [comment]
“ I don't want to document it on http://facebook.github.io/buck/ until I get some external confirmation that this is the right way to go.”

@bolinfest：Is it the time to document it?

**Comment by tbroyer** [comment]
FYI, I copied from Buck how you configure GWT for my [gwt-maven-plugin](https://github.com/tbroyer/gwt-maven-plugin) (very few properties exposed, and `compilerArgs`, `jvmArgs` and `systemProperties` for further customization needs).

Please note however that `strict` has been renamed to `failOnError` in GWT, with `strict` still being recognized as an alias. Maybe you'd want to use the new naming before documenting it.
Also, GWT 2.8 will add `--setProperty` (gwtproject/gwt@d4f4f4229accfdc29b79cce924ad26cc91e8057a) that you might want to eventually expose on the build rule.

**Comment by sdwilsh** [comment]
We now have integration tests for this provided by @shs96c as well.  If someone wanted to submit a pull requests for documentation for these rules, we'd happily take it.
