### ISSUE TITLE
Current state of buck project / IntelliJ integration

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1225]
Also posted this in the Google Group, but maybe Github is a better place for this?

--------

Hi,

We're using Buck as the build tool for our Java repository. Our repo contains a number of executables and tests that we run through both IntelliJ and the command line, and being able to run code from IntelliJ is important to our developer workflow. We're still using the "old" buck project / .iml file generation, with a custom change to allow the addition of resource folders in IntelliJ: https://github.com/Addepar/buck/commit/7350b59d49948b734492b062623e7c595774633a .

From reading old issues like https://github.com/facebook/buck/issues/350 and https://github.com/facebook/buck/issues/351, it seems like Buck wanted to change IntelliJ project generation to a new version that "builds through Buck instead of IntelliJ," but I'm not clear on what this means, or what the changes are. The documentation doesn't seem to have changed in any way, either.

So, if we switch to the new project generation:
1) Will we still be able to run/debug executables and tests from IntelliJ?
2) Will we still be able to generate multiple IntelliJ modules with dependencies on each other?
3) Does the new project generation support resource folders in IntelliJ modules? (If not, we can probably open a PR to add this feature)
4) Does the new project generation only use jars in `buck-out/`, or does it continue to put jars into the IntelliJ "output_url" specified in the .buckconfig?
5) Does project_config continue to map to exactly one .iml file, or will it create an IntelliJ module per target within the BUCK file?
6) Is it a good idea to stick to the "one project_config per BUCK file" approach? If not, what do you recommend? (We noticed that the Buck repo doesn't use buck project at all, and instead has a pre-generated .iml file checked in; is that preferred for some reason?)

Also, I have another tangential question: Why do the docs list project_config under Android but not under Java anymore?

Thanks,
Damien

**Comment by styurin** [comment]
Hello,

The current project generation (which used to be the experimental) does not use `project_config` targets. It tries to build IntelliJ modules using information from targets like `java_library`, `java_test`, etc. We currently do not maintain the deprecated project generation and plan to remove it at some point.

1. We do not build and run tests inside of IntelliJ using the capabilities provided by IntelliJ. However, we use Buck plugin that basically runs `buck build` or `buck test` inside of IntelliJ. So you can try the current project generation and see if it lets you to build code the way you do it right now. If not, you can try to use the Buck plugin.

2. Yes. There is an option to merge modules into bigger modules if these modules are under common root. We use this option to reduce the number of modules because IntelliJ performs poorly with large number of module. It however breaks the dependencies.

3. Yes, it does support that. We have some reports about some features not working properly and we plan to address these issues.

4. I am not 100% certain, but it looks like the current project generation doesn't use `output_url` from `.buckconfig`.

5. As I said, the current project generation doesn't use `project_config`. Instead, we use targets as sources for iml files. If squashing modules is disabled (see #2), the project generation creates one iml file per target. If two targets are in the same directory, these targets are merged into one iml.

6. In general, the preferred configuration is to have one target per directory. For example, if you have two `java_library` targets with different java version in the same directory, the project generation has no way to separate files in these two targets and would use one setting that can lead to error in IntelliJ if source code doesn't match the language level setting in iml.

Using manually created iml files is preferable when there aren't many change in buck dependency tree or there is only one app in the repo.

Not sure about the docs, we plan to remove it soon so it probably doesn't matter.

By the way, I recently added a message about removal of the deprecated mode. Did you see it?

**Comment by jiangty-addepar** [comment]
Thanks for the information! We're still running our fork (which is very, very far behind master) locally, so I haven't really seen the message about the deprecation removal.

We have a pretty decent number of applications in our repository and often add new modules / change dependencies, so it seems like we may need to continue generating .iml files.

Relatedly, it seems like the Buck repository itself uses one root-level .iml file, allowing IntelliJ to essentially not think about dependencies at all and just treat everything as one big IntelliJ module; that's probably not recommended if we are running multiple applications from the same repository, right?

Re: your answers to 5 and 6: currently we often have BUCK files that contain multiple `java_library` / `java_test` / `java_binary` targets, but you're saying it's preferable to put one target per directory? I guess we have some refactoring to do :)

We'll be trying out switching to the latest version of Buck and using the new project generation, so I'll ask again if any new questions pop up!

**Comment by styurin** [comment]
> that's probably not recommended if we are running multiple applications from the same repository, right?

In general yes, but if your repo is not big, you can try to use checked in iml files. I'd say if it's less than a hundred of iml files, you can live with that, but it won't scale well if the number of modules is growing.

> you're saying it's preferable to put one target per directory?

Yes. It's not a blocking issue, but don't be surprised when you get some issues with these modules. If these targets use the same java language level and have the same type (no Android target together with java targets), it should work fine. Also, dependencies can be broken if you use these targets to break dependencies cycles in buck.

**Comment by jiangty-addepar** [comment]
We're past 500 iml files, so I guess that's why our performance is slowing down :(

The targets all have the same language level and type, so hopefully they'll work for now while we change to a longer-term solution with smaller BUCK files.
