### ISSUE TITLE
NameError: name 'thrift_library' is not defined

### ISSUE THREAD

**Issue by chaitanya9186** [facebook/buck#1258]
I was trying to build https://github.com/shaochuan/buck-fbthrift-example
But getting thrift_library not found error.

Is this implemented? If not how can I get it to work.

Thanks in Advance

**Comment by Coneko** [comment]
Sorry, the thrift target types have been removed recently (7f1fc34d28b6a76813279d751b5cb243398519f2).

To ease migration, you can update to fed2a70b17025de19aa8d2bbf3bb120b9a432c9d and set the `project.thrift_target_types_enabled` setting to `false` in `.buckconfig`.

If you use thrift in your project you can implement the thrift target types with `genrule`.

**Comment by ccascone** [comment]
Hi @Coneko is there any chance support for thrift target types will be added soon again? If not, why was it removed in the first place?

**Comment by Coneko** [comment]
Sorry we're not adding them again, we implemented them in build defs in our repos where we use thrift.

I don't know if we can easily post them anywhere, @andrewjcg ? Maybe even in a non-working state as a reference implementation?

**Comment by ccascone** [comment]
@Coneko that would be great, thank you!

**Comment by ccascone** [comment]
@Coneko any chance you can publish somewhere your build defs for building with thrift?

**Comment by Coneko** [comment]
cc @andrewjcg, @yiding

**Comment by yiding** [comment]
The one we use internally is a bit complex, I'll let @andrewjcg talk about that one if he wants to. 

The general gist of it (but not an actual gist..):

* Make a genrule that includes all the thrift files as srcs...
* The genrule will invoke fbthrift compiler with each file by itself...
* You create one genrule per OUTPUT file that was created (since the thrift compiler creates a directory of files). This genrule just copies a file out of that directory and use it as its own output. (We probably want a better way to express this, either in the original `genrule` or in `export_file`).
* Using those genrules representing individual files, you can construct a cxx_library rule with srcs and headers fields filled with those genrule outputs.

If I get a simple working example code, I'll post it here.

**Comment by ccascone** [comment]
Thanks @yiding, that worked!

Instead of creating one genrule per OUTPUT file (my thrift file produces far too many java files), I did the following:

```
genrule (
    name = 'thrift-gen',
    srcs = [
    ':dummy-thrift-file',
    ],
    bash = '$(location :thrift-exe) --gen java $SRCDIR/dummy.thrift && mv gen-java $OUT',
    out = 'dummy-thrift-java-dir',
)

java_library (
    name = 'dummy-java-lib',
    srcs = glob(['../thrift-gen/dummy-thrift-java-dir/**/*.java']),
    deps = [':thrift-gen', '//lib:libthrift]
)`

**Comment by supercoolgreatcoder** [comment]
any update on this? thrift_library() rule was essential feature of buck build.

**Comment by yiding** [comment]
We have open sourced some of the internal buck 
python definitions we use for things like thrift over in the  https://github.com/facebookexperimental/buckit/ repo, check out in particular https://github.com/facebookexperimental/buckit/blob/master/infra_macros/macro_lib/convert/thrift_library.py
