### ISSUE TITLE
Buck does not compile Java on UNC paths

### ISSUE THREAD

**Issue by p0deje** [facebook/buck#1269]
I've had an issue when using buck in Selenium project on Windows. It fails to work correctly inside network directories. @shs96c pointed out that it might be a problem with UNC paths, so I prepared a Vagrant box to reproduce this behavior.

**Prerequisites**

* [Vagrant](https://www.vagrantup.com) is installed (tested on 1.9.3)
* [VirtualBox](https://www.virtualbox.org) is installed (tested on 5.1.18)

I was testing this on macOS Sierra, but host OS should not make any difference.

**Steps to reproduce**

1. First, need to prepare Vagrant VM for usage:

```bash
$ git clone https://gist.github.com/0122dca0a0f5e33732c656a047732853.git
$ cd 0122dca0a0f5e33732c656a047732853
$ vagrant up # it will take a while
```

2. Once VM is provisioned, you can connect to it from VirtualBox using *Vagrant* user with *vagrant* password.
3. When you're inside VM, start a command prompt and execute the following:

```cmd
> cd C:\vagrant\selenium
> .\..\..\buck\bin\buck build //java/client/src/org/openqa/selenium/security:security
```

**Expected result**

Buck successfully builds target.

**Actual result**

Buck fails to build target with an error:

```
BUILD FAILED: //java/client/src/org/openqa/selenium/security:security failed on step javac with an exception:
java.lang.IllegalStateException
java.lang.RuntimeException: java.lang.IllegalStateException
```

[full output](https://gist.github.com/p0deje/0122dca0a0f5e33732c656a047732853#file-buck-output)

**P.S.**

Sorry for a complicated test case to reproduce, I tried to extract Selenium buck targets into something simpler but lack Java knowledge.

Don't forget to clean up your local environment:

```bash
$ vagrant destroy
$ vagrant box remove mwrock/Windows2012R2
```

**Comment by ilya-klyuchnikov** [comment]
Buck on windows is not supposed/prepared to work with UNC paths in general. Do you really need to put selenium on UNC path here?

Two workarounds for this particular build:
1. Clone selenium into `c:\selenium`, not into `c:\vagrant\selenium` OR
2. I you use `c:\vagrant\selenium` - run `c:\buck\bin\buck build //java/client/src/org/openqa/selenium/security:security -c log.chrome_trace_generation=no`

The reason is that buck on windows use hardlinks (symlinks on windows is not so easy in general case because of setting this up correctly with privileges). And hardlinks do not work with UNC paths. In particular, chrome-like trace generation (which is on by default) uses links. Passing `-c log.chrome_trace_generation=no` turns off this tracing.

**Comment by p0deje** [comment]
> Do you really need to put selenium on UNC path here?

I'm setting up a Vagrant box to make it easier to test Selenium on Windows while still allowing to develop it on host OS (macOS, Linux). To have it I need to use a synced folder to propagate changes from host OS to a guest one. The default synced folder on VirtualBox is mounted as a network directory. Most of other options for syncing folders requires additional software (SSH for RSync, NFSD for NFS, etc.) so it's the easiest option.

> Passing -c log.chrome_trace_generation=no turns off this tracing.

Tracing is annoying, but it's not fatal. The worst part is that it actually fails to compile:

```BUILD FAILED: //java/client/src/org/openqa/selenium/security:security failed on step javac with an exception:
java.lang.IllegalStateException
java.lang.RuntimeException: java.lang.IllegalStateException```

**Comment by v-jizhang** [comment]
Hi, I'm closing this issue because it has not been updated for more than 3 years. Thanks
