### ISSUE TITLE
platform_linker_flags not working correctly?

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#1290]
I'm trying to customize my build using platform specific libraries.
Unfortunately i can't get it working on debian nor osx. 
For some reason `platform_linker_flags` are only matching on `default`.

```python
#BUCK 
cxx_binary(
  name = 'foo',
  header_namespace = 'foo',
  srcs = glob([
    'src/**/*.cpp',
  ]),
  headers = subdir_glob([
    ('include', '**/*.hpp'),
  ]),
  platform_linker_flags = [
    ('^linux.*', ['-lbar'])
  ],
)
```

buck version: adc0f78a68db45334098ac083171c7c2ebc32a8c (v2017.03.29)
`uname -s` returns Linux
in java: `System.getProperty("os.name")` returns 'Linux' as well.

**Comment by njlr** [comment]
Can confirm the same issue on macOS - the platform is "default"

**Comment by voznesenskym** [comment]
Confirmed - Ditto for us. Let me know if you need an example project created.

**Comment by Coneko** [comment]
What is the command you are running? This might only work if you explicitly run `buck build target#linux-x86_64`.

**Comment by njlr** [comment]
I get the error when running just `buck build :my-target`. Do we have to specify the target for every build? Seems like it would be more streamlined if the platform macro expanded to the actual host platform by default.

**Comment by Coneko** [comment]
I don't know, depends on whether it works if you expand it manually. If it doesn't it could be another issue.

**Comment by njlr** [comment]
I have made a small C++ project here: [https://github.com/njlr/buck-platforms](https://github.com/njlr/buck-platforms). 

Here are my results on macOS: 

```
  buck run :hello
  Hello from default

  buck run :hello#macosx-x86_64
  Hello from macOS

  buck run :hello#linux-x86_64
  Unrecognized flavor in target //:hello#linux-x86_64 while parsing //BUCK
```

**Comment by nikhedonia** [comment]
I can confirm. On Linux i have the same behavior but the other way around:

```
  buck run :hello
  Hello from default

  buck run :hello#linux-x86_64
  Hello from linux

  buck run :hello#macosx-x86_64
  Unrecognized flavor in target //:hello#macosx-x86_64 while parsing //BUCK

```

**Comment by Coneko** [comment]
Yep, then it's what I mentioned above.

cc @andrewjcg, @Ktwu was either of you two looking at this?

**Comment by Coneko** [comment]
cc @mzlee as well.

**Comment by nikhedonia** [comment]
Any updates? - as more people and packages depend on flavors, this is becoming a bigger annoyance...

**Comment by ttsugriy** [comment]
The reason for current behavior is that [platform is matched against a flavor](https://github.com/facebook/buck/blob/315cbf70ff082450c3bbc3608c074418b247be5e/src/com/facebook/buck/cxx/CxxFlags.java#L91) and by default that flavor is [default](https://github.com/facebook/buck/blob/315cbf70ff082450c3bbc3608c074418b247be5e/src/com/facebook/buck/cxx/toolchain/CxxPlatformsProvider.java#L111). I don't know a context behind this, so I can't say if it's intentional or not. If nobody picks this task up, I'll try take a look hopefully later this week.

**Comment by ttsugriy** [comment]
In fact there is even a [comment](https://github.com/facebook/buck/blame/315cbf70ff082450c3bbc3608c074418b247be5e/src/com/facebook/buck/cxx/toolchain/CxxPlatformsProvider.java#L97-L99) about this behavior:
```
// Finalize our "default" host.
// TODO(kelliem) The host flavor should default to a concrete flavor
// like "linux-x86_64", not "default".
```

**Comment by nikhedonia** [comment]
is anybody working on this ?

**Comment by andrewjcg** [comment]
Yeah, Buck doesn't setup host-specific build platforms (it's basically just "default" for the host platform, and Android and iOS specific platforms for everything else), which makes this kind of thing a pain.

Some possible short-term ways forward, depending on what your trying to do:
1) If you don't really care about cross-compilation, you can probably get using some logic in the BUCK file itself to detect the OS type (e.g. with `import platform; platform.system()`) and add flags to plain old `linker_flags` instead.
2) Setup you're own `linux` and platform in `.buckconfig`.  Since Buck doesn't yet support configuring a host-dependent `cxx.default_platform` value, this would unfortunately require an explicit flavor being set for each build.

**Comment by njlr** [comment]
I had a go at fixing this here: https://github.com/facebook/buck/pull/1562
