### ISSUE TITLE
ResourceUnion picks placeholder ids instead of real ids.

### ISSUE THREAD

**Issue by runningcode** [facebook/buck#1326]
I have module A with this declaration
```<item name="string_name" type="string"/>```
and module B with this declaration:
```<string name="string_name">foo</string>```

Module C depends on Module A and B. 
I have resourceUnion on.

How does resource union seems to always pick the placeholder id instead of the real id.

Here is a sample demonstrating the issue: https://github.com/uber/okbuck/compare/master...runningcode:no/placeholder?expand=1

cc @dreiss we discussed this in slack a couple weeks ago. Let me know if I can help.

**Comment by dreiss** [comment]
Thanks for the repro.

I looked into this a bit further.  It looks like the resource merging code in gradle takes care of this before the resources are ever shown to aapt.  I tested out the resource merger that we're using in Buck for android_aar, but it didn't do the same, so we need to find the code in gradle that has this logic.

If you can find it, that'd be awesome.  Otherwise, if you could send the most simple gradle project possible that exhibits this behavior (ideally with two values files that each override strings in the other), that would help me get started with the search.  Otherwise, I'll narrow down a small repro from the branch you posted above.

**Comment by dreiss** [comment]
For anyone following along, we're discussing this directly.  By switching the string with the item, we've found a case where Buck produces the proper string but gradle selects the empty one.  Nelson is investigating further.

**Comment by cwoodwar6** [comment]
What was the conclusion here?

**Comment by dreiss** [comment]
I think we were never able to find a case where Buck violated the "dependent overrides dependency" rule, and @runningcode  was just going to refactor their code to eliminate the need for placeholders.
