### ISSUE TITLE
Add some extra information to aid a test runner in caching the results

### ISSUE THREAD

**Issue by anotherchrissmith** [facebook/buck#1362]
Test result caching was removed in
https://github.com/facebook/buck/commit/0fc321f6bf14f66c78551e10d75bd446310e9f44

@Coneko : "More advanced test running capabilities should not be in Buck core, but should be implemented in external test runners. If you wish to write such a test runner we can discuss how to pass caching information to it."

Please could you share a few pointers for how to do this.  Many thanks.

**Comment by anotherchrissmith** [comment]
@Coneko ?

**Comment by marvinarroz** [comment]
@Coneko , I'd also like to hear if you have any pointers to share about implementing caching in an external test runner. With the change to remove caching, our CI servers now run the full test suite for all PRs. 

I would appreciate some guidance in getting us back to the behavior we had before

**Comment by Coneko** [comment]
The idea was to expose the tests' rule keys in the json file passed to the external test runner, so that the external test runner could use them to figure out whether the test was the same as a previous test run or not.

I'm not sure if it was ever implemented, I haven't worked on the project in a while.

You might still be able to call `NO_BUCKD=1 buck targets --show-rulekey <target>` in your external test runner to get the rule key.

Note that assuming the same rule key means the test results are going to be the same isn't correct though, and it's the reason test caching was removed: test results can be affected by external factors that buck wouldn't know about, especially if they're integration tests.
