### ISSUE TITLE
genrule's deps are missing

### ISSUE THREAD

**Issue by yuriy-yarosh** [facebook/buck#1368]
So, according to the existing docs, every buildrule has a set of `deps`.
But why `genrule`'s deps have had considered useless and had been removed in the first place ?

I'd personally love using back as an asset processor via `genrule` with `deps` so I could chain `optipng` commands, or even use it to rebuild and refresh docker images. There are multiple generic use cases for the `genrule` stanza.

I simply don't get it.
As for me, it's an inconsistency.

Maybe there's some other way ?

**Comment by Coneko** [comment]
You can specify the inputs to the genrule using `$(location )` macros as explained here: https://buckbuild.com/function/string_parameter_macros.html.

So for example if you want to copy a bunch of files you can put `cp $(location :file1) $OUT && cp $(location :file2) $OUT` or something like that.

**Comment by yuriy-yarosh** [comment]
@Coneko, sure thing, but what if I want to run two `genrule`'s simultaneously as a dependencies of a third one ?

**Comment by mikekap** [comment]
@yuriy-yarosh you mean like:
```
genrule(name='foo', out='foo_out', cmd='echo foo > $OUT')
genrule(name='bar', out='bar_out', cmd='echo bar > $OUT')
genrule(name='baz', out='baz_out', cmd='cat $(location :foo) $(location :bar) > $OUT')
```

**Comment by Coneko** [comment]
Note that due to Buck's caching model, thinking of when targets are being run or executed and how to control that using dependencies doesn't map intuitively to how it actually works. It's simpler if you think of inputs and outputs.

This is one of the reasons we removed `deps` from `genrule`: some users were used to the task based mental model that other build systems use, for example ant, and were using genrules with deps to replicate that but then hitting all sorts of issues with the caching.

The location macros make it much more explicit that you're passing the output of certain rules as inputs, so it's less surprising when the output is retrieved from cache and the genrule is never executed.

**Comment by yuriy-yarosh** [comment]
Thank you @Coneko.
