### ISSUE TITLE
IntelliJ plugin parsing issue

### ISSUE THREAD

**Issue by bfreis** [facebook/buck#1423]
Hello,

I've installed the IntelliJ plugin, and it seems like it has some issue when parsing BUCK files. If I declare very simple rules, it works fine. But as soon as I try to, say, define a function, or a variable, or a list comprehension, it shows a parse error, and then the entire file loses syntax highlighting.

Is this a known issue? Any workarounds?

I thought of creating an external .py file so that IntelliJ would understand the Python syntax, but then... it fails on all of the BUCK specific syntax (genrule, etc).

I'm using:

```
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Buck for IDEA, v2.9
```

Thanks
Bruno

**Comment by JonShemitz** [comment]
Bruno, I'm sorry for the slow reply: we don't monitor GitHub directly, and I just got pinged about this  issue by the "on-call" engineer.

This _is_ a known issue. The `BUCK` file syntax highlighting is fairly simplistic, relying totally on getting a valid PSI (JetBrain's language-independent syntax tree) representation. Clearly, IJ can highlight files with multiple serious syntax errors, but this requires [more 'smarts' on the part of the plugin](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support.html).

Given that most `BUCK` files are pretty simple, and given that most `BUCK` file editing just involves adding a dep or two, adding more robust syntax highlighting doesn't seem worth the effort to us. Otoh, if you want to take this one because this really bothers you and/or you're curious about how IJ syntax highlighting works, we'd be glad to review your patch.
