### ISSUE TITLE
buck test results are incompatible with junit reports

### ISSUE THREAD

**Issue by mread** [facebook/buck#143]
Both the output from "buck test --xml out.xml" and the output in gen/ are incompatible with normal junit test results processors like ant's JUnitReport task and Jenkins build results processor.

Is there any particular reason for this?

Can anyone recommend  a way of easily generating the reports?

**Comment by davido** [comment]
Every one who is targeting java platform has a toolchain that suports and expects junit format. So I would really expect the Buck to povide something like:

  buck test --xml-junit [..]

At very least would you consider to host stylesheet transformation utility, like one in: [1] so that not every project would need to add this bucklet as a git submodule?

* [1] https://gerrit-review.googlesource.com/69762

**Comment by kageiit** [comment]
@mread can you post the xslt stylesheets for the conversion here?

**Comment by Zetten** [comment]
I've added an approach in https://gist.github.com/Zetten/1e2f26cd48d144c972ba687c27dc25f5, also adapted from the bucklets xsl, with a python lxml wrapper (unlike bucklets which does the processing with a downloaded jar).

This approach is more script-y and produces one converted file per input. So if the end goal is to get reports into SonarQube, it's up to the caller to make sure that the transformed files are named "TEST-foo.xml" for compatibility with the Sonar-Java Surefire report sensor.

**Comment by mread** [comment]
@kageiit Here's the xslt I use: https://gist.github.com/mread/9b1902734b4910adf2d6029cc5d68a31
