### ISSUE TITLE
genrule's query_outputs macro should allow inputs to be found

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1520]
Using the `inputs` function. This would allow one to find all the source files of a target without needing to do anything crazy.

**Comment by asp2insp** [comment]
Can you give an example of how you would like this to work and what you would like to accomplish? Right now, `query_outputs` and `query_targets` explicitly only support fetching lists of build targets, in order to build a dependency graph, so anything which is not a build target cannot be returned.

Internally, we've often solved problems related to sharing sub-structure of rules by defining a macro. Would this work in your case?

**Comment by shs96c** [comment]
Sure. I want to build a source jar containing all the sources of files within a given part of my source tree (basically, third party deps are in a `//third_party` folder and source in `//java`). The jar crosses maven boundaries, so `#maven,src` won't work, but I can find them using:

`buck query "filter(\.java, inputs(filter(//java/, deps(//java/client/src/org/openqa/selenium:client-combined))))"`

It'd be easy to put that into a genrule that then strips the prefix of the root of the project (possibly using the `$(location)` macro, and magically have everything work.

**Comment by asp2insp** [comment]
That makes sense. I don't think `query_outputs` is the correct vessel for this, but perhaps a new query macro, ie `query_attributes` or `query_inputs` macro would serve. Happy to help with a PR. It should be straightforward to implement a new macro which extends: [QueryMacroExpander](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/rules/macros/QueryMacroExpander.java)
