### ISSUE TITLE
Xcode project generated swift header is in buck-out instead of DerivedData

### ISSUE THREAD

**Issue by robbertvanginkel** [facebook/buck#1540]
With the new changes to project generation, the location for the generated swift header is set with `DERIVED_FILE_DIR` to something like `buck-out/xcode/derived-sources/<target>-<hash>`. As an effect of this, when you clean the build folder in Xcode it does not clean this header generated by the xcode buildsystem. 

To keep artefacts in the out folder of the build system they're created by, I think this should be in a subdirectory of `$BUILT_PRODUCTS_DIR` rather than `buck-out`.

**Comment by milend** [comment]
Thanks for flagging this, @robbertvanginkel. This was done intentionally but I agree with your reasoning and I'll get this amended soon.

**Comment by milend** [comment]
As we spoke about this offline, the reason for the file to be placed inside `buck-out` is that we need to know the full path in advance. Putting it inside `$BUILT_PRODUCTS_DIR` would be tricky because we have to guess where Xcode would place the files (and this can be affected by Xcode settings and the Xcode build system used). Trying to replicate Xcode's hashing behaviour would be fragile and prone to breakage in the future, so I think we should keep things predictable for now.
