### ISSUE TITLE
maven_repositories configured but... how can i use it?

### ISSUE THREAD

**Issue by DavidGDD** [facebook/buck#1564]
I've seen in the documentation the maven_repositories config (https://buckbuild.com/concept/buckconfig.html#maven_repositories) but i dont find anywhere how can i use this config to get download the dependencies from the maven repository.

I search in the build rules list and find nothing relative to maven. I'm trying to bring my spring-boot project from maven to buck but its hard without documentation...

**Comment by sdwilsh** [comment]
Did you see https://buckbuild.com/rule/remote_file.html?

**Comment by DavidGDD** [comment]
Yeah of course, but it only download a single file, not? What happend with the dependencies of this jar?

I mean, with the maven repo config and a remote_file per first level dependency of my project is enough?

**Comment by sdwilsh** [comment]
You need to list all of your dependencies and their dependencies, etc. 
That's just how Buck works.

**Comment by ttsugriy** [comment]
@DavidGDD, Buck intentionally explicitly requires all inputs to be explicit and you'd have to create targets for every dependency in your Buck repository. This behavior is by design, although we realize that it complicates imports of Maven dependencies. Ideally Buck would provide a tool for importing Maven dependencies similar to https://docs.bazel.build/versions/master/generate-workspace.html but unfortunately we currently do not have bandwidth to do so.
