### ISSUE TITLE
Proposal: maven_library

### ISSUE THREAD

**Issue by bhagyas** [facebook/buck#1607]
Proposing a maven_library to import maven dependencies with Maven system artifact resolver.

**Comment by bhagyas** [comment]
Example artefact resolution : https://github.com/apache/maven-resolver/blob/master/maven-resolver-api/src/test/java/org/eclipse/aether/artifact/DefaultArtifactTest.java

**Comment by sbalabanov** [comment]
There is not sufficient information in this proposal. Could you please post what exactly is to be changed, what is the purpose of the change, and provide a couple examples or may be link a discussion thread?

**Comment by ttsugriy** [comment]
you should already be able to use [remote_file](https://buckbuild.com/rule/remote_file.html#url) to download remote files including maven artifacts. In general it's bad for builds to have anything outside of repository, since it can lead to build flakiness. Also, in case you'd like to make a proposal please use a proper format for it, that includes a background with context and proposed solution with APIs and usage examples.

**Comment by bhagyas** [comment]
@sbalabanov Would like to see the requirement for SHA1 specification removed. remote_file is not suited for Maven artifacts, since it adds a significant migration overhead. 

Also the ~/.m2/repository already contains the SHA1 for each Maven artifact. maven_library should automatically resolve the SHA1 from the Maven local cache.

**Comment by shs96c** [comment]
I take it you've seen the maven importer that's part of Buck already? It
uses the aether libraries to import dependencies from maven into your tree.
The original idea was for there to be a command line switch to allow it to
set the generated BUCK files up to use remote_file instead (or as well),
but I never got round to finishing it.
