### ISSUE TITLE
`buck targets --show-output` doesn't work for `command_alias` rules

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1618]
Say I have a command_alias defined in `foo/BUCK` as

```python
command_alias (
  name = 'bar',
  platform_exe = {
    'macos': ':bar-mac',
    'linux': ':bar-linux',
  },
  visibility = ['PUBLIC'],
)
```
that refers to two executable genrules `:bar-mac`, `:bar-linux`.

Then
```bash
buck targets --show-output foo/bar-linux
```
correctly shows
```
//foo:bar-linux buck-out/gen/foo/bar-linux/[filename]
```
but if I, running on Linux, do
```bash
buck targets --show-output foo/bar
```
it simply outputs
```
//foo:bar
```
without an output location. I'd like it to evaluate the alias and correctly show the output location.

Perhaps I'm misinterpreting what `command_alias` is supposed to be used for?

**Comment by jiangty-addepar** [comment]
@davidaurelio

**Comment by jiangty-addepar** [comment]
bump---has anyone taken a look at this?

**Comment by ttsugriy** [comment]
cc @davidaurelio

**Comment by ttsugriy** [comment]
David would be able to answer about the original design, but I can say why it does not show the output - it's because `CommandAlias` class extends `NoopBuldRule` that returns `null` in its `getSourcePathToOutput` method and it's the method that Buck uses to determine the rule output. it seems like it's fairly easy to fix this by implementing `getSourcePathToOutput` to return something like `platformDelegates.get(platform).getSourcePathToOutput()`, but like I've said I don't know whether it was intentional or not.
