### ISSUE TITLE
`get_base_path` is not available from SKYLARK parsed build files.

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1643]
And it's pretty useful.

**Comment by ttsugriy** [comment]
Hi, @shs96c! Thanks for your feature request! We will not provide a `get_base_path` function in Skylark parser, but we will provide its alternative [package_name()](https://docs.bazel.build/versions/master/skylark/lib/native.html#package_name). I forgot to implement it although I have implemented a deprecated variable `PACKAGE_NAME`, which we will most likely remove soon. Since it's such a trivial function to implement, I should be able to do it by the end of the day, although it might take some time for changes to get reviewed and landed. For this week you should probably be fine using `PACKAGE_NAME` though :)

**Comment by ttsugriy** [comment]
I sent a revision internally to implement `package_name` function, so hopefully it will find its way to the github soon...

**Comment by ttsugriy** [comment]
Apologies for the delay - reviewers are scarce during holidays :) Buck after  https://github.com/facebook/buck/commit/e6718eb4541678a967afe3b034945b4550e92544 has support for `package_name()` in BUCK files and `native.package_name()` in .bzl files. Please let me know if there is anything else that is missing for your use cases.
