### ISSUE TITLE
There are 300MB of checked in jars in testdata directories

### ISSUE THREAD

**Issue by jiangty-addepar** [facebook/buck#1655]
In particular, there are:
- ~30 copies of `hamcrest-library-1.3.jar` (~50KB) and `hamcrest-core-1.3.jar` (~50KB)
- ~30 copies of various `junit` jars (~250KB). Also, there are 4 different junit jars: `junit-4.11.jar`, `junit-4.12.jar`, `junit-4.8.2.jar`, and `junit.jar`.
- 4 copies of `scala-compiler-2.11.7.jar` (15MB), `scala-library-2.11.7.jar` (5.5MB), and `scala-reflect-2.11.7.jar` (4.4MB) (plus one each of `scala-compiler.jar` and `scala-library.jar`)

This might not be a pressing problem, but since I'm touching `test/com/facebook/buck/testrunner/testdata/`, I noticed a lot of these duplicates. 

For the hamcrest/junit jars: I'm not sure if these jars are necessary for the integration tests in this directory, since https://github.com/facebook/buck/blob/master/test/com/facebook/buck/testrunner/testdata/simple_testng/test/BUCK.fixture seems to be able to get away with not including any jars by including dependencies like 
```buck//third-party/java/hamcrest:hamcrest```

In general, is there a "better" way to structure integration test data to not need to duplicate these jars, especially the huge scala ones? Can we always refer to the `buck//third-party` jars? Seems like all you need to do is include `addBuckRepoCell = true` in `createProjectWorkspaceForScenario()`; are there downsides to that?

**Comment by styurin** [comment]
> In general, is there a "better" way to structure integration test data to not need to duplicate these jars, especially the huge scala ones?

I added `buck` cell with libraries used in testing exactly for that reason - to avoid duplication of libraries. We also have different versions of the same library and in most tests we can use a single version only so we should be able to remove duplicate libraries.

> Can we always refer to the buck//third-party jars?

In tests, yes.

> are there downsides to that?

It can be a little bit tricky if your library depends on other libraries mostly because buck in the main repository doesn't treat those dependencies differently. For example, if your library references `//third-party/java/hamcrest:java-hamcrest` it should exist in both the main repo and the test cell.

**Comment by styurin** [comment]
94f9d5c2ef61859584075e6fa5eaa8d0d10df905

**Comment by jiangty-addepar** [comment]
Sweet :)
