### ISSUE TITLE
rust_library build rule doesn't build anything

### ISSUE THREAD

**Issue by michaeleiselsc** [facebook/buck#1697]
I have the following BUCK file:
```
rust_library(
    name = 'Rustic',
    srcs = ['./lib.rs'],
)
```
And I have that one file, lib.rs, in the same directory (Buck will complain if I don't). However, it doesn't seem to actually build this file, because when I put garbage data into lib.rs, the buck build step says it succeeded. I also can't find an output library anywhere.

**Comment by michaeleiselsc** [comment]
I'm using Rust version 1.17.0

**Comment by styurin** [comment]
Looks like we don't test rust at all. Tests are not working at all.

**Comment by sdwilsh** [comment]
Isn't this like `cxx_library` in that we don't build anything because we 
don't know the target platform?  If that's true, you include this in a 
binary, it should build.

**Comment by michaeleiselsc** [comment]
What about if I want to build a rust crate as part of an apple_binary in Xcode? Currently, no build commands for rust seem to be generated

**Comment by michaeleiselsc** [comment]
Also, let's say I have two files in the src directory of a rust crate, lib.rs, the root, and log.rs, which can be referred to in lib.rs. My buck file is as such:
```
rust_library(
    name = 'Rustic',
    srcs = ['src/lib.rs',],
    visibility = ['PUBLIC'],
    crate = 'logger',
    crate_root = 'src/lib.rs',
)
```
It will only copy lib.rs to the temporary buck-out folder to build, and won't include log.rs. This causes the build to fail. If I try to include log.rs into the srcs array, then it will try to build log.rs independently, which is not what's supposed to happen and will also fail.

**Comment by sdwilsh** [comment]
Buck requires you to declare your dependencies and sources.  If you want 
`log.rs` to be part of the crate, you need to include it in your `srcs`. 
  If it's meant to be something you need to depend on, you need to 
ensure you have a `rust_library` that you add to your `deps` that 
includes it as a source.

I don't know how the rust stuff interacts with the apple rules, but I 
wouldn't be surprised if it's untested, and therefore doesn't work.

**Comment by michaeleiselsc** [comment]
The issue is that if I add it to srcs then buck will try to compile it with rustc, which is not what I want. In rust, you only want to compile one file, in this case, lib.rs, which imports other files as needed. So I can either copy it over and have it cause a compile failure, or not copy it over and then lib.rs can't find it. So it's different from, say, a C++ library.

**Comment by sdwilsh** [comment]
I'll have to defer to @jsgf on this.  It's been a while since I've 
looked at Buck's rust support.

**Comment by jsgf** [comment]
It looks like there are two things here:
1. `rust_library` does nothing unless you specify a flavour
2. you need to specify all the sources your target depends on, but buck will only pass the root module source to rustc.

By default, `rust_library` will do nothing unless you give it a flavour to specify the target. Normally you'd build a `rust_binary` and have the library targets build as needed. You can set one explicitly with the `buck build //mytarget#flavour` syntax; the flavours are the same for C++ targets (or `#check` for quick syntax/typecheck builds).

You need to add all your sources to `srcs`. Buck will identify the root module and pass it (alone) to rustc, or complain if it can't identify it (either because it's not `lib.rs` (`main.rs` for executables) or named after the crate name).

You can use `crate_root` to explicitly set the top-level module, but you still need to include all the sources in `srcs`. (If you're including non-source things like binaries or text, you should put those in `srcs` too.) 

> If I try to include log.rs into the srcs array, then it will try to build log.rs independently, which is not what's supposed to happen and will also fail.
> ...
> The issue is that if I add it to srcs then buck will try to compile it with rustc, which is not what I want

Could you provide the log output from buck? That sounds very unexpected; we don't see anything like that. (I assume you're running a current version of Buck? The Rust support changes regularly.)

@styurin:
> Looks like we don't test rust at all. Tests are not working at all.

Tests need an installed rust toolchain. I've been meaning to raise that.

**Comment by michaeleiselsc** [comment]
[bucktest.zip](https://github.com/facebook/buck/files/1612744/bucktest.zip)

**Comment by jsgf** [comment]
You need to specify "timer" as a dependency in `deps = []`.

**Comment by michaeleiselsc** [comment]
It says that deps only works for `rust_library` and `rust_prebuilt_library` dependencies. What about a crate from crates.io, how can I use one of those?

**Comment by jsgf** [comment]
Yeah, that's tricky. There's no integrated support for cargo or crates.io as yet. You could do something like use `genrule` to invoke cargo, to produce the rlib file from crates.io, reference that output file as the input to `rust_prebuilt_library` and then use that as a dependency.

But I haven't tried that out.

**Comment by SirWindfield** [comment]
Generating the rlib file would still need to be done by calling `cargo build` on the project that uses that library. So you basically do not generate any advantage from using buck instead of writing a shell script directly that invokes `cargo build` in the right order.
@jsgf Maybe I am not aware of a way to actually just compile a crate without having to have it as a dependency in a project.

**Comment by jsgf** [comment]
As I mentioned https://github.com/jsgf/rust-buck-skeleton/issues/1#issuecomment-414776556, the way we do this is to pre-build third-party deps and commit the .rlib files, then build with buck against those.
