### ISSUE TITLE
use absolute paths for debug symbols to fix IDE breakpoints

### ISSUE THREAD

**Issue by sheldonneuberger** [facebook/buck#1719]
Android Studio and XCode both set breakpoints based on absolute paths when you click in an editor gutter to set a breakpoint. However, buck uses relative paths for its debug symbols, so setting breakpoints in the IDE for artifacts compiled with buck doesn't work.

To support this, I intend to add an option to buck to enable absolute paths for debug symbols. Does anyone have an alternative way of making IDE breakpoints work seamlessly?

**Comment by ttsugriy** [comment]
References to environment where binaries were produced are intentionally removed by scrubbers since they make remote caching ineffective,  build rules non-hermetic and non-repeatable which is against what Buck was created for. In general IDEs should not force usage of absolute paths and provide a way to configure a CWD when running a debugger.

Maybe there is a way to solve this problem without making builds non-hermetic, but unfortunately there isn't one on top of my head.

**Comment by sheldonneuberger** [comment]
Setting a cwd for relative path resolution in the debugger sounded like the
correct approach to me but I was surprised to find no setting for this in
Studio or lldb. What are others doing to debug native buck builds in
Android Studio?

**Comment by ttsugriy** [comment]
Unfortunately I've never used Android Studio, so I don't know, but I was under impression that `lldb` 's `cwd` is easy to control by launching it from that directory or using a platform shell as described in https://stackoverflow.com/a/43351550/1548477.

**Comment by sheldonneuberger** [comment]
I spoke too soon on this, there is an lldb command to do path replacement. `settings set target.source-map . /thepath`

This will replace the first path with the second path. In our case, we use a dot and it works to resolve relative paths to the second path given.

You can type that command each time you start an lldb debugging session in Studio. Just need a way to make that happen automatically now.
