### ISSUE TITLE
Jars built using `JarBuilder` do not mark directories properly

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#1790]
Steps to reproduce (in Buck's own source):

```
buck build src/com/facebook/buck/io
zipinfo buck-out/gen/src/com/facebook/buck/io/lib__io__output/io.jar | head -3
```

Expected output:
The `META-INF` entry is marked not only as `META-INF/`, but `zipinfo` should also indicate that it's a directory. Ideally, this directory would be user, group, and world readable and executable.

Actual output:
```
Archive:  buck-out/gen/src/com/facebook/buck/io/lib__io__output/io.jar
Zip file size: 15960 bytes, number of entries: 20
-rw----     2.0 fat        0 bl defN 85-Feb-01 00:00 META-INF/
```

The directory is not marked as a directory in the zip entry extended attributes, and is not marked as executable, meaning that if the user unpacks the directory they won't be able to `cd` into it.

**Comment by sbalabanov** [comment]
Why should it have the unix attribute? I do not believe Jar specification requires that.
The problem is, if we write Unix attributes to jar archive, then Buck also sets the minimum version required to unpack the zip to be unx:
https://github.com/facebook/buck/blob/c24aa0986b46a19aa6445c9351940081f45c7ea9/src/com/facebook/buck/util/zip/EntryAccounting.java#L149
This can potentially break other scenarios. Each ZIP implementation may read this field and act accordingly, for example, refuse to decompress.
Java itself detects that entry is a directory only by looking to a trailing slash.
