### ISSUE TITLE
Buck complaining about Java AWT

### ISSUE THREAD

**Issue by 0legg** [facebook/buck#1799]
When running buck-powered build, sometimes it complains of java version:
```
[WARNING][buck.py:76] You're using Java awt, but Buck requires Java 8.
Please follow https://buckbuild.com/setup/getting_started.html to properly setup your local enviroment and avoid build issues.
```

Here is `java -version` output:
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

JAVA_HOME environment variable point to JDK8 as well. JDK8 is installed via `brew install caskroom/versions/java8`

**Comment by 0legg** [comment]
https://github.com/facebook/buck/commit/97c755ed89010cdd8b06ce4c29a5422390a5cefd can be a root cause.

**Comment by kageiit** [comment]
cc @ttsugriy

**Comment by ttsugriy** [comment]
looking...

**Comment by ttsugriy** [comment]
it's a warning and would not affect a build correctness, but it's bad to have it and I'll take care of it asap.

**Comment by ttsugriy** [comment]
I'm somewhat puzzled because the warning is produced based on the output of `java -version` invocation and the output you've shared does not mentioned `awt` anywhere. Can you please modify `_get_java_version` method in `programs/buck.py` to dump the raw output of `java -version` invocation and share it? I suspect that there is something weird with your setup.

**Comment by ttsugriy** [comment]
sorry for the inconveniences

**Comment by ttsugriy** [comment]
should be fixed by https://github.com/facebook/buck/commit/2405866ee9bd8e794505a674e76067125b5a726b Thanks for your patience!
