### ISSUE TITLE
Building a cgo library with C code that references Go code fails

### ISSUE THREAD

**Issue by monty-uber** [facebook/buck#1808]
I have this scenario set up in an example repo here: https://github.com/monty-uber/cgo-buck-example/tree/master/go-calls-c-which-calls-go

When building the go_binary rule, the build fails with the output:

```
go-calls-c-which-calls-go/call_go.c:2:10: fatal error: '_cgo_export.h' file not found
#include "_cgo_export.h"
         ^~~~~~~~~~~~~~~
```
_cgo_export.h is the header file generated by cgo from the Go code that is called from C. The go toolchain supports this as is.

**Comment by linzhp** [comment]
Updating @monty-uber's BUCK file as follow:

```python
go_binary(
    name='cgo-buck-example',
    srcs=['main.go'],
    deps=[':call_go'],
)

cgo_library(
    name='call_go',
    headers = ["call_go.h"],
    srcs=['export-to-c.go',
        'call_go.c']
)
```

**Comment by ChuntaoLu** [comment]
I spent some time looking into the issue, but couldn't come up a fix with my limited understanding of buck internals and cxx_lib compilation. I did find a couple of issues in the source code:
- the [documentation](https://buckbuild.com/rule/cgo_library.html#srcs) says .go source files are compiled with cgo compiler, however, buck evokes cgo tool with cgo_library srcs as [arguments](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/features/go/CGoGenSource.java#L139-L142) while the cgo command expects arguments to be .go files. This would not be a problem if cgo_library srcs contain only .go files.
- buck passes [incorrect directory](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/features/go/CGoGenSource.java#L114) with the `-I` flag to cgo, the directory buck passes is the parent directory of the correct header directory. Notice in the following example the header file is in the a nested sub-directory:
```bash
# from buck debug log
cd /Users/lu/cgo-buck-example && GOROOT=/usr/local/Cellar/go/1.11.2/libexec GOOS=darwin 
GOARCH=amd64 GOARM='' /usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64/cgo 
-importpath /Users/lu/cgo-buck-example -srcdir /Users/lu/cgo-buck-example 
-objdir buck-out/gen/go-calls-c/call_from_go#cgo,cgo-gen-sources,default/gen
 -- -I/Users/lu/cgo-buck-example/buck-out/gen/go-calls-c/call_from_go#cgo,default,headers
go-calls-c/cgo_source.g
```
```bash
➜  cgo-buck-example git:(master) ✗ tree /Users/lu/cgo-buck-example/buck-out/gen/go-calls-c/call_from_go#cgo,default,headers     21:39:56
/Users/lu/cgo-buck-example/buck-out/gen/go-calls-c/call_from_go#cgo,default,headers
└── go-calls-c
    └── call_from_go.h -> /Users/lu/cgo-buck-example/go-calls-c/call_from_go.h
```
- I suspect the `-I` flag is also incorrect in the C code compilation step of the cgo_library rule, instead of a directory, buck passes a .hmap binary file:
```bash
# from buck debug log
/usr/bin/clang -x c -fPIC -fPIC
 -I buck-out/gen/go-calls-c/call_from_go#cgo,cgo-first-step,default,private-headers.hmap 
-I buck-out -Wno-unknown-attributes -Xclang -fdebug-compilation-dir 
-Xclang . '-fdebug-prefix-map=/Users/lu/Uber/cgo-buck-example=.' 
-o buck-out/gen/go-calls-c/call_from_go#cgo,cgo-first-step,compile-pic_cgo_export.c.o8114ac55,default/call_from_go#cgo,cgo-gen-sources,default/gen/_cgo_export.c.o
 -c -MD -MF buck-out/gen/go-calls-c/call_from_go#cgo,cgo-first-step,compile-pic-_cgo_export.c.o8114ac55,default/call_from_go#cgo,cgo-gen-sources,default/gen/_cgo_export.c.o.dep buck-out/gen/go-calls-c/call_from_go#cgo,cgo-gen-sources,default/gen/_cgo_export.c
```
I am not familiar with C compilation, but the Clang man page says the `-I` flag should specify a directory:
```man
-I<directory>
              Add the specified directory to the search path for include files.
```
    
I was able to fix the first two issues, but couldn't sort things through for the third one. Hope above information helps.

**Comment by mkaczanowski** [comment]
Since the cgo_library doesn't accept the c files, the above BUCK file won't simply work (also the first file in srcs is used to infer package name - this fails if you pass C file).

I fixed that issue in: https://github.com/facebook/buck/commit/dfbc952df89505a49df0d2036d229cd7c2fb00e0

Now you should be able to access "_cgo_export.h" from within "call_cgo.c". This is one step forward

**Comment by mkaczanowski** [comment]
main.go currently with buck can't contain `import "C"` cgo directive. You need to create intermediate library instead.

For example I applied patch to @monty-uber repro: https://pastebin.com/raw/itEyPXrV

and it works fine now

**Comment by linzhp** [comment]
Awesome! It works. Added the working example to [here](https://github.com/linzhp/buck_go_examples/tree/master/c_call_go) for future reference.

Thanks for the fix!
