### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by LegNeato** [facebook/buck#1895]
I put up two PRs that would be good to message about. Right now it is basically impossible to follow along with Buck changes unless you read every commit. We should maintain a running changelog.

**Comment by LegNeato** [comment]
If the project wants this, happy to put up a PR with the initial content.

**Comment by ttsugriy** [comment]
yes, changlog would be very welcome, so please feel free to create an initial version :)

**Comment by styurin** [comment]
I doubt we'll have time for that. Having changelog would mean everyone should be updating it, otherwise there is no point in keeping it.

**Comment by ttsugriy** [comment]
I'm sure there will be times that some changes do not have to be included in the changelog, but I believe there is value in having this. Otherwise there is no meaningful information to attach to the release notes :( I think it would not be a too big of a problem to ask people making large changes to include a line describing what they are solving.
