### ISSUE TITLE
AutoService generated META-INF files is not getting packages into the kotlin_library's output jar.

### ISSUE THREAD

**Issue by raviagarwal7** [facebook/buck#1897]
https://github.com/google/auto/tree/master/service

Works on a `java_library` jar but fails on `kotlin_library`.

**Comment by sbalabanov** [comment]
As you may have noticed :) we did not have bandwidth to work on this. Please come up with PR if this is still relevant.

**Comment by jbarr21** [comment]
@sbalabanov Why is this a won't fix? I understand that you don't have bandwidth, but can we still leave this open for potential contributors?

**Comment by styurin** [comment]
Let's keep it open since it's a current issue. We can close it when it's fixed or when it's not relevant anymore.

**Comment by hzsweers** [comment]
I see this is still marked as `wontfix`?

**Comment by zach-klippenstein** [comment]
This issue seems to also prevent the use of certain Kotlin reflection APIs (e.g. `isSealed`). The reflection library defines a couple service loaders that are accessed lazily, and they're missing from Buck builds. I'm observing this on an older version of kotlin (1.2.61), but newer versions define the same service loaders so I expect the issue affects them as well.

**Comment by kageiit** [comment]
cc @thalescm to make sure its still on his radar :)
