### ISSUE TITLE
cgo_library link failure when setting link_style to static

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#1961]
After setting `link_style` of a `cgo_library` rule to be "static", the linking stage will fail.

To reprouduce:

1. Check out [this commit](https://github.com/linzhp/buck/commit/12fdf2cd1ba798ec1a324072100a5e0af33994d5)
2. Run `buck test //test/com/facebook/buck/features/go:integration`

@mkaczanowski

**Comment by mkaczanowski** [comment]
This is known issue and tbh I am not sure how to fix it. The linking will fail because in cgo_library you can specify the link_style where during go link the static_pic is enforced, so likely this is causing the link failure.
Check out: GoDescriptors.java$240,340

AFAIK go build uses the STATIC_PIC by default and frankly speaking I am not sure in which conditions static linking is valid.

Likely I will enforce the STATIC_PIC (even rust code does it today because of -pie) to avoid problems like this.

On the other hand I am not sure keep link mode between cgo_library and cgo_binary. For example if two cgo_libraries have static and static_pic link modes, in which mode should the go_binary be linked?

**Comment by linzhp** [comment]
I am not concerned about not being able to use STATIC (otherwise I would have sent you a PR already :D ) Eliminating invalid option to avoid issues sounds good to me.
