### ISSUE TITLE
Cgo packages cannot have a package name different than its folder name

### ISSUE THREAD

**Issue by linzhp** [facebook/buck#1999]
Go allows a package name different from its folder name. However, we have to tell cgo the package name so it generates .go files with right package declaration. It was possible to do that at revision fdb121f6f803ad14c7ab77c0381e81da6ae06fab, but after #1994, it is no longer possible. As a result, we cannot build github.com/mattn/go-sqlite3 with Buck anymore.

Steps to reproduce the error:

1. Checkout the sqlite branch of [my fork of buck](https://github.com/linzhp/buck/tree/sqlite)
2. Run [this test](https://github.com/linzhp/buck/blob/sqlite/test/com/facebook/buck/features/go/GoBinaryIntegrationTest.java#L315)

As a comparison, Go toolchain is able to build the same package:

```bash
cd test/com/facebook/buck/features/go/testdata/cgo
GOPATH=$(pwd) go run src/different_package/cli/main.go
```

In order for the Go toolchain to build the package, we cannot change the import statements in `main.go`.

**Comment by linzhp** [comment]
cc @vitarb

**Comment by mkaczanowski** [comment]
> Go allows a package name different from its folder name

did you mean buck?

---
I have tested it locally and it works well for me (can't repro):
```
=== BUCK
go_binary(
    name = "bin",
    srcs = ["main.go"],
    deps = [":cgo"]
)

cgo_library(
    name = "cgo",
    package_name = "github.com/mattn/sqlite3",
    srcs = ["cgosrc.go"],
    deps = ["//pat/to/lib/c:lib"],
)

=== cgosrc.go
package sqlite3

/*
#include "path/to/lib/c/lib.h"
*/
import "C"

func Test() {
	// Simple C function call.
	C.f0()

	// Call with constant.
	C.f1(5)
}
=== main.go
package main

import "github.com/mattn/sqlite3"

func main() {
	sqlite3.Test()
}
```

I have also added some test file to the go_srcs and included the whole cgo_library from another BUCK file. It works fine.

Also the package_name is used in the integration tests:
https://github.com/facebook/buck/blob/master/test/com/facebook/buck/features/go/testdata/cgo/src/mixed_with_c/BUCK.fixture#L9

Could you update the example in one repo / dir (with the "new" cgo_library invocation) so I can reproduce?

**Comment by mkaczanowski** [comment]
@linzhp thanks for providing the test case and please paste the stacktrace next time. The problem is not that package name is not being respected but the package name you provided is invalid.

I have used your test from here:
https://github.com/linzhp/buck/commit/9ee81d113972b6cc618b9be2f24d097be3a7046f

The error:
```
buck-out/gen/src/different_package/go-sqlite/lib#cgo,cgo-gen-import,default/gen/_cgo_import.go:1:9: syntax error: unexpected go, expecting name
```

The contents of imported file:
```
package go-sqlite
```

**go-sqlite** is invalid package name by go toolchain (can't have hypen). In addition to that the go-package sources (ex. cgosrc.go) defines the **sqlite** package, so that is also mistake since you're trying to use **go-sqlite** instead.

After updating your test to:
```
=== main.go
import "different_package/sqlite"

=== go-sqlite/BUCK.fixture
package_name='different_package/sqlite',
```

it works well. Try to change the package name to sqlite :)

**Comment by mkaczanowski** [comment]
After long discussion with @linzhp on slack we got to the root of the problem, which is frankly speaking very non-obvious.

Because cgo package is always embedded in go binary generated by "go build" the package name is not expected to be the same as the binary package name.

"go build" would infer the package name from the source files (not the location / directory name) and use it as "cgo" package_name.

For example:
```
go_library(
    name='lib',
    package_name="github.com/mattn/go-sqlite3",
    srcs=['doc.go', 'sqlite3_func_crypt.go', 'sqlite3_go18.go'],
    cgo=':cgo_lib',
    visibility=['PUBLIC']
)

cgo_library(
    name='cgo_lib',
    package_name = "sqlite3",
```

This used to work before, because the package_name is different for cgo and go libraries. The former is **not** the import path (ex. github.com/whatever/go-sqlite3) but **sqlite3** which "go build" would infer from the source files.

The solution is to add extra argument such as:
```
declared_package_name = "sqlite3"
```

to cgo_library

**Comment by nemith** [comment]
I am still a bit confused on the detail here

` package_name="github.com/mattn/go-sqlite3",` isn't really the package name.  It's the import path.  Adding declared_package_name seems like we are making up terminology because we named the package_name variable wrong.

**Comment by mkaczanowski** [comment]
Yes "github.com/mattn/go-sqlite3" it's import path, but in buck terminology it's going to be called package_name (see: https://buckbuild.com/rule/go_library.html).

Changing this is a lot of work both internally and for the OSS world. If we were able to run go list, this wouldn't be even needed.
I believe this is the best we can do atm

**Comment by linzhp** [comment]
Buck is actually running "go list" to filter the platform specific Go files. Maybe we can get package name out of it too.

**Comment by mkaczanowski** [comment]
Possibly...

**Comment by mkaczanowski** [comment]
It's used in only one place (CGoGenImport.java) so likely it can
