### ISSUE TITLE
Is buck's glob function caching results?

### ISSUE THREAD

**Issue by nikhedonia** [facebook/buck#2023]
I have a BUCK file with 100s of glob-expressions and parsing takes more than 3mins.
I'm certain that I can optimize my BUCK file by refactoring and refining my globs.
However I was wondering what optimisations are already built in ?

**Comment by ttsugriy** [comment]
Buck has a lot of glob implementations depending on whether watchman is available and Skylark or Python DSL is used. When Skylark is used all glob invocations are cached. If Python DSL is used only watchman-based implementation caches results.

We can certainly add caching support for Python DSL globber that is used when Watchman is not available, although I strongly recommend not using it since it's very slow.

**Comment by nikhedonia** [comment]
I'd like to mention that switching from python-dsl to skylark reduced the parsing time from over 3mins to less than 3s.

**Comment by ttsugriy** [comment]
this is awesome, @nikhedonia! Thanks for letting us know! Would you still like to have caching for Python DSL internal globber?

**Comment by nikhedonia** [comment]
@ttsugriy depends on a couple of factors:
- when are you making skylark the default?
- how much engineering effort does it entail?

It would be definitely a nice to have as parsetimes become quite painful on larger projects.
We are also not ready to move the buckaroo ecosystem to skylark - I think we are 3 months away from that.
