### ISSUE TITLE
looking for more documentation for Go build rules

### ISSUE THREAD

**Issue by groob** [facebook/buck#2105]
Hello, I'm evaluating buck vs bazel for a project built with Go. I was able to follow the official guides from Bazel and convert my Go 1.11 project that uses modules and Make. 
For reference, here's my conversion to bazel: https://github.com/kolide/launcher/pull/375/files

I'm now trying to do this with Buck but I'm stuck. 
- Is it possible to reuse the starlark rules from bazel? What would I need to do to import https://github.com/bazelbuild/rules_go into a buck build? If this is the wrong approach, what is the correct one? 
- How should one import a third party library? How can we convert an existing go.sum file to `go_library` with buck?

**Comment by ttsugriy** [comment]
Hello @groob,

Unfortunately at the moment Buck does not support extensions and as such you won't be able to use Bazel Go rules for a Buck project. There is a native support for common Go use-cases, like [go_binary](https://buckbuild.com/rule/go_binary.html) and [go_library](https://buckbuild.com/rule/go_library.html), but for non-trivial setup your best bet is buck slack channel and/or @mkaczanowski.

**Comment by groob** [comment]
@ttsugriy how would I go about joining the Buck slack?

**Comment by ttsugriy** [comment]
@groob, you can create a github issue requesting invitation or you can ping someone from Buck team, like @styurin asking him to send you an invitation :)

**Comment by groob** [comment]
Does this issue count, or should I open a separate one?

**Comment by ttsugriy** [comment]
@groob, the title of this issue is unlikely to suggest that you're asking for the Slack channel invitation :) At the same time Buck team members see these messages, so this may be enough. A separate issue would be more visible though.

**Comment by mkaczanowski** [comment]
@groob talked with @linzhp on slack (it's great since @linzhp is adapting buck with go feature at Uber). I am closing this issue, since most of the questions are answered.

A few takeaways:
1. buck doesn't manage vendor packages. Bazel supports fetch from remote endpoints where in buck you'd have to create your vendor repo and manage the deps (internally we have small to do it).
2. we didn't think about go modules, yet
3. currently there is no feature to convert bazel go rules to buck. There are similarities between go_binary/go_library in buck and bazel, so it should not be too difficult to come up with some conversion mechanism (NOTE: cgo_library might not be trivial, though).
4. [genrule](https://buckbuild.com/rule/genrule.html) is used to create "custom rules", for example thrift generator or mockgen (with limitation for now, see [proposal](https://github.com/facebook/buck/issues/2010))
