### ISSUE TITLE
Support application code and libraries for android applications

### ISSUE THREAD

**Issue by saleehk** [facebook/buck#223]
Ant and Gradle have a concept of "application code" and "libraries", but Buck only has libraries. The application code gets one special privilege, however: its resource ids are constants, which means that they can be used in switch statements and annotations.

This would able things like this with ButterKnife:

```
@InjectView(R.id.button1) Button button1;
@InjectView(R.id.button2) Button button2;
```

**Comment by rowillia** [comment]
I'm looking at adopting Buck now, but unfortunately I've hit a stopping point due to this issue.  @dreiss  had some ideas in irc as to how to solve it (have `android_binary` take in srcs which get graph enhanced to an android_library rules that has the final merged `R.java`.

I've also considered forking ButterKnife to support generating the code as part of Buck's build process, but unfortunately I don't have time for either :/

**Comment by nicks** [comment]
Why is it that "R constants in Android library projects cannot be assumed to be final"? 

The gradle/android stuff seems to be OK using final R constants, and I'm curious how Buck's compilation model is different.

**Comment by sdwilsh** [comment]
@nicks, TLDR: Ant and Gradle structure Java sources differently from Buck.

Ant and Gradle have a concept of "application code" and "libraries", but Buck only has libraries.  The application code gets one special privilege, however: its resource ids are constants, which means that they can be used in switch statements and annotations.  Realistically, this wouldn't be too hard to support with Buck.  I'll morph this issue for that.

Note at this still won't work with library code: https://github.com/JakeWharton/butterknife/issues/100

**Comment by bolinfest** [comment]
We discuss this a little bit in our exopackage tutorial: https://buckbuild.com/article/exopackage.html#refactor-r-constants.

Since this is something that Android formalized (http://tools.android.com/tips/non-constant-fields), it doesn't seem crazy to me to expect an Android tool to work in the presence of library projects.
