### ISSUE TITLE
Python external depenency

### ISSUE THREAD

**Issue by omry** [facebook/buck#2304]
Hi,
I dug through the docs and the issues and did not find anything relevant.

Does buck support PyPI packages as dependencies?
If so, how can I specify them?
If not, how does people usually deal with dependencies on other Python projects?

I saw prebuilt_python_library, which seems to be in the right direction, but also seems to suggest that I need to keep copying of the prebuilt libraries in my source tree (or otherwise it's not clear to me how to indicate that I want to depend on a specific pypi pakcage version and have it downloaded from pypi at build time).

**Comment by philipjameson** [comment]
Buck does not support this directly.

You can either download whls yourself and put them in the source tree, or use a remote_file() target to download them at build time. They can then be used as the src for a prebuilt_python_library. You will need to maintain urls for those packages on your own and setting up the dependencies, as pip does not provide useful dependency information. This is not likely something that will be directly included in buck, though may in the future be exposed in a more generic way to let one fetch third-party packages.

**Comment by omry** [comment]
Can you expand about "pip does not provide useful dependency information" ?

Using pip show I am getting all the dependencies of a package:

```
$ pip show omegaconf
Name: omegaconf
Version: 1.3.0
Summary: A flexible configuration library
Home-page: https://github.com/omry/omegaconf
Author: Omry Yadan
Author-email: omry@yadan.net
License: UNKNOWN
Location: /miniconda3/envs/hydra36/lib/python3.6/site-packages
Requires: PyYAML, six
Required-by: snapdump, hydra
```

**Comment by philipjameson** [comment]
pip is nondeterministic, and cannot figure out dependencies until you install a package. pip show only works for things that you've installed. Having to install something in order to find out how to actually use it doesn't really fit with Buck's model.  There is also no structured output format for the dependency graph if you /do/ install a package making any integration that one might try to do fragile at best. Last time I attempted to add that to pip, they were not amenable to the changes.

As we also do not have a pre-build environment to install non-hermetic/non-deterministic packages, and we don't really want to add special hacks in for pip, directly to buck, writing your own tooling around pip that then freezes the whls is likely the best way to do this. This is what facebook has done.
