### ISSUE TITLE
There is an exception in the first build buck

### ISSUE THREAD

**Issue by kinkenrin** [facebook/buck#2362]
When I install the buck，run this commandLine "buck build --show-output buck"
has an Exception here:

Command failed with exit code 1.

stderr:
    When running javac.
    When building rule //src/com/facebook/buck/jvm/java/abi/kotlin:kotlin.

How can I solve it ?

**Comment by v-jizhang** [comment]
Please try "./bin/buck build --show-output buck".
What is your jdk version? Do you have any detailed error messages?

**Comment by kinkenrin** [comment]
> Please try "./bin/buck build --show-output buck".
> What is your jdk version? Do you have any detailed error messages?

error messages:
![image](https://user-images.githubusercontent.com/16291652/72129285-a55fc880-33b0-11ea-902f-b498245c7fa9.png)

my jdk version is here:
![image](https://user-images.githubusercontent.com/16291652/72129345-dc35de80-33b0-11ea-8461-7370ccc84958.png)

Do you have any solution?

**Comment by lovestorymeetsvivalavida** [comment]
I have the same problem.

**Comment by v-jizhang** [comment]
Thank you for reporting this issue. While we are looking into it, please follow the instructions at https://buck.build/setup/getting_started.html to clone and build another buck. Make sure you see "BUILD SUCCESSFUL" from ant build first then run the buck build.

**Comment by lovestorymeetsvivalavida** [comment]
> Thank you for reporting this issue. While we are looking into it, please follow the instructions at https://buck.build/setup/getting_started.html to clone and build another buck. Make sure you see "BUILD SUCCESSFUL" from ant build first then run the buck build.

Still fail the same place, what‘s the root cause?

**Comment by v-jizhang** [comment]
@lovestorymeetsvivalavida, We're unable to create a repro. What is your OS? Thanks

**Comment by lovestorymeetsvivalavida** [comment]
> @lovestorymeetsvivalavida, We're unable to create a repro. What is your OS? Thanks

MacOS 10.15.2

**Comment by v-jizhang** [comment]
Please take a look at the file `./.circleci/config.yml`, that's where we config a MacOS machine for CI testing. I'll use the CI test "`mac_build_openjdk8`" as an example. Hope this helps.

**Environment:**
- MacOS with XCode 11.3.1 installed.
- `export BUCKROOT="/Users/<username>/buck"`
- `ANDROID_SDK="/Users/<username>/android-sdk"`

**Steps:**
- `git clone https://github.com/facebook/buck.git`
- Install OpenJDK8
- Install Android SDK
    `mkdir -p "${ANDROID_SDK}"`
   ` cd "${ANDROID_SDK}"`
   ` curl -O "https://dl.google.com/android/repository/sdk-tools-darwin-4333796.zip"`
    `unzip "sdk-tools-darwin-4333796.zip"`
    `export PATH="${ANDROID_SDK}/tools/bin:${PATH}"`
    `echo 'y' |sdkmanager --install tools`
    `echo 'y' |sdkmanager --install platform-tools`
    `echo 'y' |sdkmanager --install "build-tools;28.0.0"`
    `echo 'y' |sdkmanager --install "platforms;android-23"`

- The following script installs GoLang on MacOs:
```
   cd ~
   curl -O "https://storage.googleapis.com/golang/go1.10.1.darwin-amd64.tar.gz"
   sudo tar -xzf go1.10.1.darwin-amd64.tar.gz -C /usr/local
   rm go1.10.1.darwin-amd64.tar.gz
   export PATH="${PATH}:/usr/local/go/bin"
```
- Install Python
```
   brew install pyenv
   pyenv install -s 3.6.2
   pyenv global 3.6.2 system
   export PATH="$(pyenv root)/shims:${PATH}"
```
- Run ant build, do not installed the latest ant because it depends on JDK13
   To install ant 1.9, do
    `brew install ant@1.9`
    `export PATH="/usr/local/opt/ant@1.9/bin:${PATH}"`
    Run ant build:
    `cd ${BUCKROOT}`
    `ant`
- Run buck build
   `export PATH="${ANDROID_SDK}/tools/bin:${PATH}"`
   `./bin/buck build buck`

**Comment by CoXier** [comment]
Is there any solution?

**Comment by v-jizhang** [comment]
> Is there any solution?

No yet, please see #2466 for more informations.
