### ISSUE TITLE
how do you deal with code formatters and auto-fixing linters?

### ISSUE THREAD

**Issue by BrianHicks** [facebook/buck#2449]
Hey there! I'm looking into build tools and I'm curious about one feature in particular: code autoformatters. These are things like `go fmt` or `elm-format`, or even `rubocop --auto-correct` that modify the original source files.

It could be that I'm not looking in the right place or haven't read exactly the right document yet, but how would you deal with tools like this in Buck?

**Comment by v-jizhang** [comment]
As I know buck does not deal with any formatting tools, it just builds the source files. Linters can be applied in code reviewing.

**Comment by philipjameson** [comment]
To expand on this a little more, there are a few ways this can be done, none of which are done directly in buck. This is because buck rules only get access to a working directory, and rules are expected to be hermetic. Something that modifies the source repository would not be hermetic.

There are a couple of ways to do this with external tools, though. The buck repo uses tests that run as part of CI to ensure that all source files are linted. This just ends up being a CI step that fails if the files are formatted poorly. This could very easily be a tool that has a buck rule, and is run as part of CI with `buck run //tools:linter -- /path/to/repository`. 

Inside of FB we use a tool that's substantially similar to Arcanist from Phabricator (https://secure.phabricator.com/book/phabricator/article/arcanist/). This can be run locally, and also runs during our (additional, internal) CI. I've also used this for my personal projects, and would definitely recommend it.
