### ISSUE TITLE
`cmd_exe` attribute in genrule() definition implies code duplication

### ISSUE THREAD

**Issue by davido** [facebook/buck#267]
It was pointed out in review to this change [1] that there is a lot of place for improvement in copy/paste approach (of `cmd` to `cmd_exe` code blocks with only few adjustments) for supporting Buck build on other patform:

```
genrule(
  name = 'api',
  cmd = ';'.join(
    ['cd $TMP'] +
    ['ln -s $(location %s) .' % n for n in API_DEPS] +
    ['zip -q0 $OUT *']),
  cmd_exe = ' && '.join(
    ['cd %TMP%'] +
    ['cp $(location %s) .' % n for n in API_DEPS] +
    ['zip -q0 %OUT% *']),
  deps = API_DEPS,
  out = 'api.zip',
)
```

Can we avoid code duplication?

[1] https://gerrit-review.googlesource.com/#/c/65600/1/BUCK@28

**Comment by spearce** [comment]
I would be happy to change the *NIX cmd version to use ' && ' as the command separator if that makes the cmd_exe side easier to transform.

We would also be OK with changing $TMP and $OUT to $(TMP) and $(OUT) if that made a regex looking for $(TMP) and replacing with %TMP% for cmd_exe easier. Buck already parses $(location) and $(exe) within cmd. Similarly "parsing" $(TMP) to insert the "platform variant" for the few variables Buck makes available to genrules would be fine with us.

The cp vs. ln -s thing shows up sometimes in our genrules. I proposed a $(LN_S) variable that does "ln -s" or "cp" depending on platform. I also proposed monkeypatching genrule() in Gerrit's build to make that work for us since it may be more project specific that we need so many of these ln -s genrules and we prefer not to copy everything on *NIX.

**Comment by sdwilsh** [comment]
Buck does expand `$ENV_VAR` to that variables contents on Windows so you can try to share today.  As for `ln`, I'm not sure I like "just copy if we are on Windows" to be honest.  Zip is also something that doesn't exist on Windows by default, but we've solved that in our own tests by creating a small `python_binary` and using python's built in zip functionality.

In general, I've found that whenever I want to avoid this, I just write a small python function, which is usually more maintainable and even testable than some shell scripting.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sdwilsh** [comment]
We now have `zip_file` rule, which covers a bit of what you are asking.  The bonus here is that it produces a zip that is actually cacheable (doesn't have timestamps in it, etc).

https://buckbuild.com/rule/zip_file.html

**Comment by davido** [comment]
Thanks. Before using it for implementation of Gerrit build on the other platform we would want to clean up our build implementation and switch to `zip_file` where possible. Particularly, we are using `zip` to overcome Buck design limitation that `genrule` can only have one single output artifact: [1].

I guess this hack can be now replaced with just:

```
  zip_file(
    name = 'api',
    srcs = API_DEPS,
  )
```

* [1] https://github.com/gerrit-review/gerrit/blob/master/BUCK#L11,L30

**Comment by sdwilsh** [comment]
You know that `genrule` can also output a directory, right?

**Comment by sdwilsh** [comment]
> I also proposed monkeypatching genrule() in Gerrit's build to make that work for us since it may be more project specific that we need so many of these ln -s genrules and we prefer not to copy everything on *NIX.

I think this might be a better solution.


I'm going to close this since it would be hard to write something that would work for all platforms.  If you have specific things you'd like to see, we should file issues on each of those, but as written this task is done or you should hack up in your own repo.
