### ISSUE TITLE
android_binary() documentation misses information about use_split_dex

### ISSUE THREAD

**Issue by vovkab** [facebook/buck#308]
There is no information about use_split_dex and other related options on documentation page for android_binary(): 
http://facebook.github.io/buck/rule/android_binary.html

**Comment by sdwilsh** [comment]
We currently only support it for exopackage.  At the time we wrote it, Android didn't support split dexes natively. With Lollipop that changed.  We didn't document it, because it wasn't possible for non-FB people to use the feature, and we didn't want to open source our split dex loading code.

I'm not sure if the support library handles this now, or if it just works with Lollipop and newer devices.

**Comment by sdwilsh** [comment]
I'm going to close this in favor of #309

**Comment by vovkab** [comment]
Can you please move your answer there, so we can continue conversation in #309?
