### ISSUE TITLE
buck project does not generate intellij project compiler output

### ISSUE THREAD

**Issue by llj098** [facebook/buck#351]
IntelliJ version: 14.1.3
buck version: 01160561c57df309f39e71e06b9c25082f769c03

Steps:

1. run the command `buck project`
2. open the project in IntelliJ
3. build -> rebuild project
4. intellij error shows: the output path is not specified for modules: xxx ...

My workaround:

1. open Project settings -> project
2. choose a dir for the `project compile output`  
3. works.

Is it a bug ?

**Comment by sdwilsh** [comment]
The current project generation is...lacking.  @marcinkosiba is reworking it all, but that's hidden behind the `--experimental-ij-generation` flag of `buck project`.  Does that help at all?

**Comment by llj098** [comment]
@sdwilsh Got it.

But the `--experimental-ij-generation` flag still does not work. You still can't rebuild the project. BTW, seems the `src-roots` in `project_config` does not work with this flag?

**Comment by sdwilsh** [comment]
@marcinkosiba is the best person to answer that, but he's mostly away this week.

**Comment by strangemonad** [comment]
@sdwilsh @marcinkosiba I'm assuming https://github.com/facebook/buck/issues/350 is the relevant meta-task describing the experimental flag?

**Comment by sdwilsh** [comment]
Correct!

**Comment by marcinkosiba** [comment]
Because buck supports a features that can't be expressed in terms of IntelliJ's build it generally no longer makes sense to build through IntelliJ. We should probably make this clearer, but the main reason we have `buck project` is so that you can edit the code, not as an export strategy. We're working on having a plugin which will allow you to conveniently invoke `buck build` and `buck test` from IntelliJ in the future.

> But the --experimental-ij-generation flag still does not work. You still can't rebuild the project
Could you elaborate? Is the generated project incorrect or does the build initiated from within `buck project --experimental` not work?

> seems the src-roots in project_config does not work with this flag?
The --experimental-ij-generation intentionally ignores project_config - we should be able to infer all of that information from the target description itself. If you're seeing problems with the package prefix in the generated project then 1f2fb48498 should fix this.

**Comment by Windyfbin** [comment]
How we generate a Intellij project by "buck project " command ?. I installed buck and build successfully, but i want to generate a project which allow to edit by an IDE.

**Comment by sdwilsh** [comment]
https://buckbuild.com/command/project.html

**Comment by Windyfbin** [comment]
Thanks you. I have read it but i need buckbone to create buck project and use "buck project --ide intellij" to generate it to an Intellij project.

**Comment by Coneko** [comment]
You can run all `buck project` commands in a project created with buckbone, the two things won't interfere.

You cannot use `buck quickstart` with buckbone, but `buck project` is a different thing.

**Comment by marcinkosiba** [comment]
I think this is sorted? Please reopen if you have further questions.

**Comment by ovanes** [comment]
I have the same issue and came across this post. Can you please, what is the flow to work with IntelliJ in general. So if I edit code I just use application target, which depends on entire project to make the build. Tests which are run, are not reflected in the default test execution tool.

But the main question, how do run a particular target in a debugger when working with the buck project/plug-in?

**Comment by ovanes** [comment]
Seems like I figured it out. After `buck project` one needs to create a sub-directory for IntelliJ output and setup it in the Project Structure (`⌘;`)  `Project Settings / Project / Project Compiler Output`. In addition verify please, that SDK was properly set.
