### ISSUE TITLE
Genrule should not implement SupportsInputBasedRuleKey

### ISSUE THREAD

**Issue by mread** [facebook/buck#427]
I don't fully understand the purpose of input-based rule keys however its use in Genrule seems to be a bad idea.

Our example is a genrule that depends on sh_binary rule. When the underlying shell script changes the genrule hash should be invalidated but the input-based rule key changes 3cb80ef284f12394e5f09299b60c088f43ee4af9 (June 2015) stops this happening.

Removing the marker interface from Genrule fixes our problem.

**Comment by Coneko** [comment]
How are your rules set up?

What do you mean your genrule depends on the sh_binary rule? Is it using it with an `$(exe )` macro?

**Comment by mread** [comment]
Yes, something like this below. I would expect a change to findbugs.sh to trigger a rebuild of my-findbugs-rule - but it doesn't.
```
sh_binary(
    name = 'run-findbugs',
    main = 'findbugs.sh',
    resources = glob( [ '*' ], excludes = [ 'findbugs.sh' ] ),
    visibility = [ 'PUBLIC' ]
)

genrule(
    name = 'my-findbugs-rule',
    srcs = glob( ['src/main/java/**/*']),
    cmd = '$(exe //build/findbugs:run-findbugs) $SRCIDR etc etc',
    out = '%s_result' % name,
    deps = [ ':run-findbugs' ],
    visibility = [ 'PUBLIC' ]
)
```

**Comment by andrewjcg** [comment]
Yeah, this is a bug in `ShBinary.getExecutableCommand()` -- it should be attaching `main` as an input used by the rule when it's run as an executable, but it's only adding in the generated shell script.  I'll put up a fix ASAP.

In general, input-based rule keys are rule keys derived from the contents of a rules' inputs (both user-provided and generated).  This differs from normal rule keys, which instead hash in the rule key of the generating rule, rather than the contents of its output.  This makes input-based rule keys more stable in the face of changes that should affect the rule (e.g. modifying a comment in a header file means we have to re-preprocess a source, but the preprocessed source is identical, so we shouldn't have to re-compile).

**Comment by mread** [comment]
Great explanation, I understand now and looking forward to seeing the effect on some of our long-running genrules.

**Comment by mread** [comment]
I'm still getting issue in this area - let me know if I need to raise a new issue in github.

I've got a genrule like this:
```
export_file(name = 'file1.txt')
export_file(name = 'file2.txt')
genrule(
    name = 'check-file-test1',
    srcs = glob( [ 'srcs/SomeSrc.java' ] ),
    cmd = 'cat $(location :file1.txt) > $OUT && cat $(location :file2.txt) >> $OUT && cat $OUT 1>&2',
    out = 'targ-file.txt',
    deps = [
        ':file1.txt',
        ':file2.txt'
    ]
)
```

This gets triggered whenever file1.txt or file2.txt are modified. As expected.

However if I modify the rule to look like this:
```
genrule(
    name = 'check-file-test2',
    srcs = glob( [ 'srcs/SomeSrc.java' ] ),
    cmd = 'cat $(location :file2.txt) > $OUT && cat $OUT 1>&2',
    out = 'targ-file.txt',
    deps = [
        ':file1.txt',
        ':file2.txt'
    ]
)
```

Then the rule is only triggered for changes to file2.txt and doesn't get run for changes to file1.txt. 

Is this expected/correct behaviour? Previously any material change to a dependency would cause a rule to be re-run.

**Comment by sdwilsh** [comment]
@Coneko has been looking at something related to this I think.  I'm pretty sure that `deps` are ignored on `genrule`, but I don't recall the reasoning.  How do you depend on `file1.txt` but don't use it in the command?

**Comment by Coneko** [comment]
Yeah I've been working on removing `deps` from `genrule` entirely.
They don't work correctly, and they don't make sense anyway: if a genrule depends on an input it means it uses it in its command somehow, if it doesn't then it's not an input.

@mread: What is the use case for having `file1.txt` in your example? `file2.txt` will be picked up as a dependency automatically since it's an argument to the `$(location )` macro.

**Comment by Coneko** [comment]
Yeah I've been working on removing `deps` from `genrule` entirely.
They don't work correctly, and they don't make sense anyway: if a genrule depends on an input it means it uses it in its command somehow, if it doesn't then it's not an input.

@mread: What is the use case for having `file1.txt` in your example? `file2.txt` will be picked up as a dependency automatically since it's an argument to the `$(location )` macro.

**Comment by Coneko** [comment]
Yeah I've been working on removing `deps` from `genrule` entirely.
They don't work correctly, and they don't make sense anyway: if a genrule depends on an input it means it uses it in its command somehow, if it doesn't then it's not an input.

@mread: What is the use case for having `file1.txt` in your example? `file2.txt` will be picked up as a dependency automatically since it's an argument to the `$(location )` macro.

**Comment by mread** [comment]
Our use case is that we have certain jobs which we want to run every commit, even if the results would normally be cached. E.g. an integration test job that has some occasionally intermittent tests so we want to re-run the job every time there's a commit so we can record the level of intermittency.

We do this by writing the current svn revision number to a file and then exposing that file via export_file() and depending on it in rules that we want to run every commit.

I know this is quite hacky however it's worked well for us so far.

I actually prefer the behaviour you're working towards so I guess we'll have to find another hack. Simply using the dependency in the cmd works fine and we can probably wrap the whole of that in a custom macro.
