### ISSUE TITLE
Xcode 7 support

### ISSUE THREAD

**Issue by milch** [facebook/buck#432]
### Description:

When you use the current HEAD version of `buck` (c2ed8543) to create an Xcode project, there are a few issues when using Xcode 7: 

- ARC is not turned on, even though the `-fobjc-arc` option is set in the `preprocessor_flags` section of the corresponding `apple_binary()`, and static asserts that check this will fail when compiling in Xcode. 
- Build & run does not work when the project is generated using the `--build-with-buck` CLI switch. 
- The header search paths aren't set correctly, so that code that depends on a C++ library cannot find its headers.

### Steps to reproduce:

- Clone the [bucksamples](https://github.com/fbsamples/bucksamples) repository.
- `cd` into the `cross-platform-scale-2015-demo` folder and run `buck project demo_app_ios` or `buck project --build-with-buck demo_app_ios`
- Open the resulting `BuckDemoApp.xcworkspace` and choose "Build & Run". 
     * Observe that in projects that were created with `--build-with-buck` the iOS Simulator does not start - and if it was already started the App will not launch. 

    * Projects that were created without `--build-with-buck` will fail with a `'common/hello.h' file not found` error.
- Inspect the `Build Settings` tab of the `BuckDemoApp` target, specifically the "Objective-C Automatic Reference Counting" option and notice that it is set to 'No'.

### Expected Results

- ARC should be turned on if I supply `-fobjc-arc` as compiler flag. Maybe there could be another switch in `apple_binary` et al. that would automatically set the correct `compiler_flags`, project settings, and other switches that are needed for ARC to work.
- The project should build and run in the iOS Simulator, regardless of if it was created with `--build-with-buck` or not.
- All headers should be found.

**Comment by sdwilsh** [comment]
Thanks for the solid issue; lots of details and steps to reproduce!  @Coneko should be able to help you out early tomorrow.

**Comment by Coneko** [comment]
1. The build settings will not show `Objective-C Automatic Reference Counting` as enabled, but the compilation will still use the setting, it's under `Other C Flags`.

2. The project builds and runs if generated with `--build-with-buck`. Note you need to close Xcode before generating the project, or Xcode will ignore the scheme on disk, keep the values it has in memory, then overwrite the scheme on close. It doesn't do this for project files so it's a bit unintuitive. Buck is supposed to show a prompt asking to quit Xcode if this is the case, but it seems not to show up when `buckd` is running.

3. The headers aren't found when generating the project without `--build-with-buck` because it assumes the headers will be exported using the apple convention of `target-name/header.h` instead of the cxx convention of `base/path/header.h`.

Thanks for reporting this, we'll have a look at both.

**Comment by Coneko** [comment]
c9f1cb6aeb381860dce101fe02eae0118d2a55c3 should have fixed the last issue.
