### ISSUE TITLE
Truncating the buck log during tests leaves a malformed file after further log entries

### ISSUE THREAD

**Issue by grumpyjames** [facebook/buck#523]
This is not an issue with buck but with a common pattern seen in the tests.

Anything that calls ProjectWorkspace.resetBuildLogFile() (or one of a couple of reimplementations) will empty the log file and set its size to 0. However, the logger still has an open file and knows its position, so further log entries are written from that position. The result is a sparse file, which has lots of null bytes at the beginning (which may or may not take up space on disk).

Since some tests seem to perform complex parsing of the log file, this seems unwise (it made DiffRuleKeysScriptIntegrationTest hard for us to debug). An alternative is to avoid truncating, but instead track the position of the log file by checking its size, and only parsing the segment which a test is interested in.

**Comment by marcinkosiba** [comment]
I'll own up to DiffRuleKeysScriptIntegrationTest. Apologies for the rubbish debugging session you had to endure because of this! Ideally we'd output the rulekey information to a separate file (like `buck audit rulekey <target> --json path/to/file`) in a sane format that the script (and anyone else) could use, but in the meantime I'll look into not truncating the log file.

Thanks for the feedback!
