### ISSUE TITLE
python dynamic import  error

### ISSUE THREAD

**Issue by xidianwlc** [facebook/buck#628]
when use __import__ in python project，the params of __import__()  can't be assigned right , when use buck run always throw a ImportError exception, do BUCK had any support for python dynamic import ?

**Comment by k21** [comment]
It is not recommended to import external Python modules because Buck is not aware that they are used and does not re-run the BUCK files when the external modules change. The recommended way is to use the [`include_defs` function](https://buckbuild.com/function/include_defs.html) which lets you execute another file in the same repo from a BUCK file.

**Comment by k21** [comment]
I hope that answered your question. Please let me know if you need any clarification.
