### ISSUE TITLE
Extend BuildTargetParser to understand cell based rules

### ISSUE THREAD

**Issue by davido** [facebook/buck#658]
Given a repository definition:

```
[repositories]
  jgit = lib/jgit
```

I would expect, that something like this should just work:

```
  $ buck build "\@jgit//:jgit"
  BUILD FAILED: Build target path cannot be absolute or contain . or .. (found //\@jgit:jgit)
```

Unfortunately it doesn't.

**Comment by mzlee** [comment]
So the underlying issue is in the CommandLineTargetNodeSpecParser which doesn't take into account the cross cell. We're currently working on this, and moving away from using '@' to specify the cross cell to prevent the '@' command line functionality from args4j. Instead, you should be able to use `jgit//:jgit`.

**Comment by davido** [comment]
Thanks! We were forced to temporarily remove jgit cross cell support in Gerrit Code Review, as we don't have a workaround for now for: #717. One it's solved we re-consider to add it again.
