### ISSUE TITLE
Autodeps doesn't work

### ISSUE THREAD

**Issue by shs96c** [facebook/buck#662]
Steps to reproduce:

git clone https://github.com/shs96c/buck.git
git checkout 0d03a7cf1e2923b913fd900ff67c98d2c00d5f62
ant clean default
buck autodeps

Notice that no files have been changed.

./bin/buck build buck

Watch the build fail while attempting to compile the SuperConsolveEventBusListener which is a little surprising.

**Comment by sdwilsh** [comment]
What version of Java are you running, by chance?

**Comment by shs96c** [comment]
Java 8.

**Comment by bolinfest** [comment]
Hi Simon!

Java 8 is what Travis-CI is using, so if you've rebased on top of a green build (I'm a little unclear at what the rebase point is for your branch), then that should not be an issue.

I see that https://github.com/facebook/buck/commit/0d03a7cf1e2923b913fd900ff67c98d2c00d5f62 pulls in a lot of the `.buckconfig` configuration. I was recently able to eliminate half of it in https://github.com/facebook/buck/commit/939c59efa1f8fc6df6b644800a61df595a340598, so you might want to rebase past that point.

Admittedly, there is a giant warning, but there are docs for `buck autodeps`: https://buckbuild.com/command/autodeps.html.

I suspect that if you are introducing new symbols that `buck autodeps` did not notice yet, then it's probably because you need to add some entries in `.buckconfig` for any new third-party JARs you have introduced. I'm working on eliminating that requirement today.

**Comment by bolinfest** [comment]
Also, if you're introducing new `java_library()` rules, then you probably want to eliminate the `deps` and specify `autodeps = True` like we do for the overwhelming majority of rules under `src/` now. (I haven't cleaned up the `test/` directory yet: I'd rather finish clearing out `.buckconfig` first.)

**Comment by shs96c** [comment]
I've not touched the listeners in the events package. It's seems like a problem for autodeps to fail.

**Comment by bolinfest** [comment]
OK, I'm not sure exactly what's going on. I can reproduce it on your fork, but I don't have the issue on my internal version of Buck.

I think there are three ways to fix it:

1. Something like https://github.com/facebook/buck/commit/820a985, so in `TestResultFormatter.java` and/or `SuperConsoleEventBusListener.java`, replace uses of `testResult.getType()` to do a local assignment first (`ResultType resultType = testResult.getType()`) to force an import statement. (Yes, I know this is lame.)
2. Add `//src/com/facebook/buck/test/result/type:type` to the `deps` like in the old days.
3. Add `//src/com/facebook/buck/test/result/type:type` to the `exported_deps` of an appropriate rule.

Also, to make sure it isn't something special with my internal version, I tried it with the open source one at the commit before the merge on your fork. This part worked fine:

```
git clone git@github.com:facebook/buck.git
cd buck
git checkout 599923e
ant clean default
./bin/buck build buck
```

But admittedly, if I ran:

```
./bin/buck autodeps
```

It went ahead and deleted a bunch of important lines from:

```
src/com/facebook/buck/event/BUCK.autodeps
src/com/facebook/buck/event/listener/BUCK.autodeps
```

That said, 599923e is from a week ago, and I've made a bunch of improvements to the heuristics for `buck autodeps` since then, so can you try rebasing on the latest master?

**Comment by bolinfest** [comment]
Hmm, though I'm seeing some weird stuff on master. @sdwilsh I think we need to add something on CI that verifies that `buck autodeps` leaves all `BUCK.autodeps` files unchanged, i.e., verify that `buck autodeps` has been run before checking something in.

**Comment by bolinfest** [comment]
I'm seeing different behavior on external vs. internal on this. Specifically, when I checkout https://github.com/facebook/buck/commit/bc1f1ae345e1b0994b0cf751fe9d69e886203dd6 publicly and run `buck autodeps`, I see changes to:

```
src/com/facebook/buck/event/BUCK.autodeps
src/com/facebook/buck/event/listener/BUCK.autodeps
```

When I check out the equivalent commit interally and run `buck autodeps`, none of my `BUCK.autodeps` files are changed.

We should probably do the silly `ResultType resultType = testResult.getType()` trick for now to get a quick fix and set up the appropriate stuff in CI to guard against this going forward.

**Comment by bolinfest** [comment]
@shs96c this should unblock you
