### ISSUE TITLE
BUCK fails to detect my code modification at v2016.02.29.01

### ISSUE THREAD

**Issue by Piasy** [facebook/buck#694]
As the title described.

My BUCK version is `v2016.02.29.01`. I create a [reproduce project](https://github.com/Piasy/BuckProjectEditDetectDemo), after first run of `buck install -r appRelease`, then edit any java code inside `app`, `firstlevellib` or `secondlevellib` module, then run `buck install -r appRelease` again, the new build doesn't contains the modification.

**Comment by Piasy** [comment]
When I roll back to `v2016.02.08.01`, it works fine.

**Comment by k21** [comment]
Thanks for the report, I have checked that the issue reproduces on the master branch as well. It looks like we are not getting modification events from Watchman. I will try to find the commit that broke this.

**Comment by k21** [comment]
Bisect points to 10942e9e65ce4905bbc7a276e4a18d1d40a2807d as the breaking commit. The problem seems to be caused by [this line in your `.buckconfig`](https://github.com/Piasy/BuckProjectEditDetectDemo/blob/52d4be61601212b9f29641cef4a7f59c1e67aaa2/.buckconfig#L10):
```
	ignore = .git, **/.svn,
```
Due to the trailing comma, the newer version of Buck parses this value as a list of 3 elements where the third element is an empty string representing the root of the repository. Removing the trailing comma fixes the issue:
```
--- a/.buckconfig
+++ b/.buckconfig
@@ -7,4 +7,4 @@
        target = android-23

 [project]
-       ignore = .git, **/.svn,
+       ignore = .git, **/.svn
```

There is a work in progress to abort the build when someone tries to build a target in an ignored directory, which would make problems like this easier to debug.
