### ISSUE TITLE
Does Buck support different applicationId for multiple build types?

### ISSUE THREAD

**Issue by chenupt** [facebook/buck#715]
There is a manifest_entries argument in the android_binary which is equivalent to defaultConfig in gradle. But I have not found the applicationId attribute in there.

**Comment by sdwilsh** [comment]
You can use an [android_manifest](https://buckbuild.com/rule/android_manifest.html) rule with a [genrule](https://buckbuild.com/rule/genrule.html) to do this on the fly.  It's how we've done this internally, IIRC.  You just reference the `android_manifest` instead of specifying a file for the `android_binary`.

**Comment by Piasy** [comment]
@sdwilsh I just found the `manifest_entries` parameter of `android_binary` rule today, but I find out that we still need add `minSdkVersion` and `targetSdkVersion` into our `android_manifest` rule's `skeleton`, otherwise the `android_manifest` rule will fail. This is still not convenient :(  

But indeed `manifest_entries` add the flexibility of change the final apk we can build.

**Comment by sdwilsh** [comment]
I think the manifest code is actually imported from AOSP.  It's possible that updating it might relax that constraint (see #299).  This isn't a priority for the core team though, but they'd probably take a PR :)
