### ISSUE TITLE
Buck still not working with NDK r11c

### ISSUE THREAD

**Issue by lucidsheep** [facebook/buck#727]
Despite #701 being closed, NDK r11c is still having issues with buck. With ndk_version = r11c and ANDROID_NDK pointing to the right location, the following error is given:

`BUILD FAILED: Supported NDK version is r11c but Buck is configured to use 11.2.2725575 with ndk.dir or ANDROID_NDK`

Issue occurring on commit 91d3fdd0ddbbf3c7008990ebf89bb5363a40d474

**Comment by michath** [comment]
The error message gives me the following information:
- Buck found a NDK with version `11.2.2725575`
- You specified your target NDK version is `r11c` based on the name of the folder `android-ndk-r11c`, as expected.

The problem comes from the inconsistency between the naming of the folder and how version is defined in `source.properties` where is stored in the form `Pkg.Revision = 11.2.2725575`. This was a change introduced with `r11*`. In previous versions, it was stored in `RELEASE.TXT` in the form of `r10c`.

The solution to this is to either let Buck find the latest NDK version or specify `ndk_version = 11.2` or `ndk_version = 11.2.2725575`. We could hack around this but it wouldn't change the fact naming convention changed with the latest NDK version and we should adapt to it.

**Comment by lucidsheep** [comment]
Was there a fix for this issue? If I set `ndk_version = 11.2.2725575` in .buckconfig I get a different error:

`BUILD FAILED: could not extract version from NDK repository at com.facebook.buck.io.ProjectFilesystem@b8d30b1e (projectRoot=/Users/kevin/android/android-ndk-r11c, whiteListedPaths=Optional.absent(), blackListedPaths=[]: /Users/kevin/android/android-ndk-r11c/RELEASE.TXT`

**Comment by FuegoFro** [comment]
It looks like that's coming from this [`readVersion`](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/NdkCxxPlatforms.java#L482) function, which indeed is only checking for the (now removed) `RELEASE.TXT` file. It seems like rather than duplicating the logic in the [`findNdkVersionFromPath`](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/android/DefaultAndroidDirectoryResolver.java#L139) function, we should re-use it, either by passing the version into the place that the `readVersion` call happens or pulling it out into a static function somewhere. I don't know enough about the code to know which approach would be preferred, but if someone wants to weigh in I'd be happy to submit a pull request.

**Comment by michath** [comment]
@FuegoFro thank you for the tip, I was unaware we were doing that. I think a0b7991a8835ccce81d83c00a584529a2c3ad0fb should fix the issue. Added bonus is not mistaking r10e and r10e-rc4 anymore. Let me know if this continues to be a problem.
