### ISSUE TITLE
Failed to create adb connection.

### ISSUE THREAD

**Issue by ZacSweers** [facebook/buck#797]
Irreversibly stuck in this issue, unplugging device, killing/restarting adb all don't seem to help. Not sure what other info I can give, so please let me know. Using `adb` by itself works fine.

`[warn ][command:807cfdd6-190c-4182-851a-dee711916ada][tid:215][com.facebook.buck.util.Console] Build failure: Failed to create adb connection.`

**Comment by hzsweers** [comment]
Periodically, it'll show this when I run `adb devices` afterward

```
adb server version (32) doesn't match this client (36); killing...
// proceeds to restart adb server, then continue to not work :(
```

**Comment by kageiit** [comment]
@marcinkosiba can you provide any insight on this?

**Comment by marcinkosiba** [comment]
@kageiit not really, that string doesn't come out of the buck codebase, so it's either libddm or adb itself that's doing the restart. Going by the error message maybe an adb version conflict due to `which adb` being different than the `adb` buck fishes out of $ANDROID_SDK?

**Comment by kageiit** [comment]
We have also observed even with the correct adb version, buck is not able to install to devices since it thinks adb connection does not exists/devices do not exist.

`adb devices` says otherwise. The problem seemed to go away after deleting the `.buckd` folder and rerunning the same command. Ill provide concrete repro steps next time this happens.

**Comment by kageiit** [comment]
We are seeing this when trying to run instrumentation tests as well

```
instrumentation test
stderr: Unable to set up adb.

       	at com.facebook.buck.step.StepFailedException.createForFailingStepWithExitCode(StepFailedException.java:62)
       	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:71)
       	at com.facebook.buck.step.DefaultStepRunner$1.call(DefaultStepRunner.java:92)
       	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:80)
       	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService$1.apply(WeightedListeningExecutorService.java:76)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
       	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
       	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)

====STANDARD OUT====

====STANDARD ERR====
```

After deleting the .buckd folder and running again the error message changes to

```
BUILD FAILED: Failed to create adb connection.
BUILD FAILED: Expecting one android device/emulator to be attached.
```

**Comment by kageiit** [comment]
The adb path is correct. I verified it by looking at the returned `adbExecutablePath` in `InstrumentationTestRunner`

This seems to be mitigated by changing `ADB_CONNECT_TIMEOUT_MS` in `com.facebook.buck.testrunner.InstrumentationTestRunner` to a much higer value like 50 seconds instead of 5.

A few possible options to look at
- We are using latest adb from platform tools 24.1.1_1
- Buck is using an older version of ddmlib
- Providing a way to increase the timeout in buckconfig

@marcinkosiba please advice

**Comment by kageiit** [comment]
We have noticed that there is a delay of atleast 25 seconds before AdbHelper can return true for `isAdbInitialized`

Here are the repro steps for this bug
- Install latest platform tools -> 24.1.1._1
- Checkout https://github.com/uber/okbuck
- Run `./gradlew okbuck` to generate buck files for the project
- Run `buck test //app:instrumentation_demoDebug_test` against `HEAD` of buck
- Test fails with cannot create adb/ cannot setup adb
- Change `ADB_CONNECT_TIMEOUT_MS` to something like `60000` instead of `5000` in both `src/com/facebook/buck/testrunner/InstrumentationTestRunner.java` and `src/com/facebook/buck/android/AdbHelper.java`
- Run the instrumentation test command again. It will succeed

**Comment by kageiit** [comment]
@marcinkosiba the error strings are definitely coming from the buck codebase because it thinks that adb is not initialized yet. I have suggested some approaches to mitigate this issue previously. let us know what the best course of action would be

**Comment by felipecsl** [comment]
I'm seeing this too. Also a bunch of these in the buck logs, not sure if it's related:

```
[2017-01-11 16:31:19.027][info ][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Server cleanly exited with status 42
583 com.martiansoftware.nailgun.NGExitException: ExitException: status 42
584     at com.martiansoftware.nailgun.NGSecurityManager.checkExit(NGSecurityManager.java:56)
585     at java.lang.Runtime.exit(Runtime.java:107)
586     at java.lang.System.exit(System.java:971)
587     at com.facebook.buck.cli.Main.runMainThenExit(Main.java:738)
588     at com.facebook.buck.cli.Main.nailMain(Main.java:1959)
589     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
590     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
591     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
592     at java.lang.reflect.Method.invoke(Method.java:498)
593     at com.martiansoftware.nailgun.NGSession.run(NGSession.java:338)
594
595 [2017-01-11 16:31:19.027][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Tearing down client socket
596 [2017-01-11 16:31:19.027][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Flushing client socket
597 [2017-01-11 16:31:19.027][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Error shutting down socket I/O (this is expected if the client disconnected a    lready)
598 java.io.IOException: com.sun.jna.LastErrorException: [57] Socket is not connected
599     at com.martiansoftware.nailgun.NGUnixDomainSocket.doShutdown(NGUnixDomainSocket.java:74)
600     at com.martiansoftware.nailgun.NGUnixDomainSocket.shutdownInput(NGUnixDomainSocket.java:60)
601     at com.martiansoftware.nailgun.NGSession.run(NGSession.java:384)
602 Caused by: com.sun.jna.LastErrorException: [57] Socket is not connected
603     at com.martiansoftware.nailgun.NGUnixDomainSocketLibrary.shutdown(Native Method)
604     at com.martiansoftware.nailgun.NGUnixDomainSocket.doShutdown(NGUnixDomainSocket.java:71)
605     ... 2 more
606
607 [2017-01-11 16:31:19.027][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Closing client socket
608 [2017-01-11 16:31:19.028][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Finished tearing down client socket
609 [2017-01-11 16:31:19.028][debug][command:null][tid:771][com.martiansoftware.nailgun.NGSession] Waiting for next client to connect
610 [2017-01-11 16:31:19.028][info ][command:null][tid:771][com.martiansoftware.nailgun.NGSession] NGSession shutting down
```

**Comment by chrislacy** [comment]
I'm seeing this also. When I follow @kageiit's suggestion and increase `ADB_CONNECT_TIMEOUT_MS` to `60000` the adb connection (usually) occurs eventually, although when it does so it often takes ~30 seconds for the adb connection to register. 

In my case, it seems the issue occurs far more often when attempting to run on an emulator. Running on a device is much more reliably.
