### ISSUE TITLE
New project generation no longer sets IDE module SDKs.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/buck#821]
Previously, the deprecated project generation would set the JDK for the entire project using:

```
[intellij]
    jdk_name = Android API 23 Platform
    jdk_type = AndroidSDK
    language_level = JDK_1_7
```

It seems like the new project generation doesn't respect these values. Is there any rationale behind this - or is it simply not implemented?

**Comment by marcinkosiba** [comment]
It's not implemented. The new project generator doesn't write the misc.xml file at all, so once you set up the SDK once in IJ it should just keep on working.
The main reason this part is non-trivial is because the jdk/sdk settings are bound to your install of IntelliJ, and will potentially vary across developers machines, so the choice is to either have a hardcoded value, which may or may not work (deprecated project), to have none (current project implementation). Another option would be to auto-detect IntellIj SDK/JDK setup and write a misc.xml that matches is, but that then requires knowing which version of IJ the user wants to open the project with (sounds like something the IJ plugin could help with).

**Comment by tonycosentini** [comment]
That makes sense.

What about individual SDKs for specific IntelliJ modules? Does that get overwritten when running `buck project`? We have a mix of Android and Java modules - when setting the global project SDK to Android, you need to manually set all of the Java modules to a non-Android JDK.

**Comment by kageiit** [comment]
> so the choice is to either have a hardcoded value, which may or may not work (deprecated project), to have none (current project implementation)

How about writing only if values are explicitly specified instead? I was also thinking of doing an sdk option per language like

```
android_sdk
java_sdk
```

This can then be set on the module xml of the corresponding targets. This way more jvm based languages can add their own sdk parameters as needed and st them in their module xml.The language level can be inferred from the source and target options set on the java/android targets, to be set on the module xml instead of misc.xml as well.

**Comment by kageiit** [comment]
@marcinkosiba I put up a PR that sets up the jdk and language level in every module.iml file instead. This achieves what @tonycosentini mentioned in the previous comment.

**Comment by styurin** [comment]
That was recently implemented, check .buckconfig docs: https://buckbuild.com/concept/buckconfig.html#intellij.

**Comment by kageiit** [comment]
#832 makes it possible to configure multiple default sdks per project based on the type of module
