### ISSUE TITLE
Way to get jacoco xml report when running with --code-coverage

### ISSUE THREAD

**Issue by kageiit** [facebook/buck#825]
`buck test --code-coverage` currently only outputs a jacoco.exec file which is not very useful. It would be great to get an option to output html and xml similar to gradle

**Comment by marcinkwiatkowski** [comment]
Html is also generated by default, you can change that by specifying  `--code-coverage-format=xml`.

**Comment by kageiit** [comment]
Where is the report located? I am only seeing `buck-out/gen/jacoco/jacoco.exec` even after i passed the `--code-coverage-format=xml` option like

`buck test --code-coverage-format=xml --code-coverage`

Running with the buck built from HEAD

**Comment by marcinkwiatkowski** [comment]
`buck-out/gen/jacoco/code-coverage/coverage.xml`, that `code-coverage` directory is defined here https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/java/coverage/ReportGenerator.java#L70

**Comment by tildedave** [comment]
@kageiit Hi there, I had a similar issue and I discovered I could get the actual cause of the problem by running buck in verbose mode.

This encountered that the actual coverage command was failing, for me it looked like this:

```
java -jar /Users/daveking/.gradle/caches/okbuck/buck/build/report-generator.jar /Users/daveking/workspace/project/buck-out/gen/jacoco/parameters.properties
```

My issue turned out to be two classes with the same name which causes Jacoco to fail.  Hope this is helpful!
