### ISSUE TITLE
prebuilt_jar fails when the jar has duplicate entries in it.

### ISSUE THREAD

**Issue by rbraunstein** [facebook/buck#84]
BUILD FAILED: //third-party/jmdns-3.4.0-jenkins-3-jar:jmdns-3.4.0-jenkins-3-jar failed on step get_class_names Optional.of(third-party/jmdns-3.4.0-jenkins-3-jar/jmdns-3.4.0-jenkins-3.jar) > buck-out/gen/third-party/jmdns-3.4.0-jenkins-3-jar/jmdns-3.4.0-jenkins-3-jar.classes.txt with an exception:
Multiple entries with same key: com/strangeberry/jmdns/tools/Browser=903578aa54046efcab5fde9f4b5f229155897dac and com/strangeberry/jmdns/tools/Browser=903578aa54046efcab5fde9f4b5f229155897dac

In this jar, some classes are duplicated:
  http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/jmdns/3.4.0-jenkins-3/

% jar -tvf ~/Downloads/jmdns-3.4.0-jenkins-3.jar | grep Browser
   709 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$1.class
   713 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$2.class
   711 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$3.class
   950 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$ServiceTableModel.class
  6297 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser.class
   709 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$1.class
   713 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$2.class
   711 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$3.class
   950 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser$ServiceTableModel.class
  6297 Tue Aug 09 13:24:14 PDT 2011 com/strangeberry/jmdns/tools/Browser.class

**Comment by brettwooldridge** [comment]
@sdwilsh I'd like to request that this issue be re-opened (and re-visited).  In our case, we do not check-in jars but instead resolve them from maven.  One of our dependencies, [org.apache.xmlbeans:xmlbeans:2.6.0](http://search.maven.org/remotecontent?filepath=org/apache/xmlbeans/xmlbeans/2.6.0/xmlbeans-2.6.0.jar), is built with duplicate class entries.

As expected, the result is:
```
BUILD FAILED: //ThirdParty:xmlbeans failed on step get_class_names with an exception:
Multiple entries with same key:
  org/apache/xmlbeans/xml/stream/Location=b010d46296931435514ab3d6237b17e03df64e5b
  org/apache/xmlbeans/xml/stream/Location=b010d46296931435514ab3d6237b17e03df64e5b
```
However, as in the case for @rbraunstein, the duplicate classes are identical, yielding the same hash.  As the zlib specification allows duplicate entries, it seems the correct handling would be to simply ignore one of the classes, provided that the hashes match.

Of course, if the classes are truly different and error is warranted.

Given that xmlbeans hasn't updated since 2013 it seems unlikely that an upstream fix will be available in a timely fashion (though we will certainly open an issue there).  At that same time, we are loath to alter our build process to accommodate a single jar issue.  Again, it seems like buck can both easily and safely resolve the issue by simply ignoring classes with identical keys and identical hashes.

**Comment by sdwilsh** [comment]
I haven't actively worked on the Buck project in over nine months, so I'm going to cc @Coneko who is my best guess for someone who might be able to respond to you, @brettwooldridge.

**Comment by Coneko** [comment]
I'll cc @shs96c and @ryandm since I have no idea about maven.

**Comment by brettwooldridge** [comment]
Thanks guys.  In the meantime I'm cooking up a pull request for review, looks like a one or two line change.

**Comment by ryandm** [comment]
This issue isn't precisely maven related, but agreed on @brettwooldridge's assessment of dissatisfaction with workarounds (which I've also seen in practice) and that allowing *identical* duplicates is practical here. A pull request would be awesome.

**Comment by brettwooldridge** [comment]
@ryandm Not that it matters so much, but the code in the pull request throws a nearly identical exception to the one previously being throw by guava.
