### ISSUE TITLE
static initialisation failures during "buck test" not dumped to console

### ISSUE THREAD

**Issue by mread** [facebook/buck#845]
When a java_test rule fails at runtime due to problems with static initialisation buck outputs:

`test exited before generating results file`

The only way I know to find out what the actual error was is to re-run the test using --verbose 4, then paste the actual test execution line into the console. At which point we can see what's output to stderr.

As normal, happy to help with a fix if someone could point me in the right direction - how can we ensure that this output is dumped to the console instead of being swallowed?

Thanks.

**Comment by k21** [comment]
The cause seems to be that `com.facebook.buck.jvm.java.JUnitStep` is a subclass of `com.facebook.buck.shell.ShellStep`, which runs the junit process in its `launchAndInteractWithProcess` method. The logic in that method says that the stdout and stderr are printed if either the exit code is not zero or the `shouldPrintStdout` / `shouldPrintStderr` method returns true. I guess junit exits with a zero exit code (?) in this case and `JUnitStep` does not override the `shouldPrintStderr` method, so nothing gets printed out. The tricky part of the problem is that we cannot just make `shouldPrintStderr` return `true`, because we only want to print the output if the results file was not generated, but we only find out later in `JavaTest.interpretTestResults`.

I think the easiest way to fix the issue would be to make junit return nonzero exit code when this happens (or figure out why the nonzero exit code does not trigger the error message to be printed).
