### ISSUE TITLE
Support macro expansion in java_library's postprocess_classes_commands

### ISSUE THREAD

**Issue by Zetten** [facebook/buck#910]
The (undocumented...) parameter `postprocess_classes_commands` for java_library targets allows the definition of an array of strings which are executed as `BashStep`s on the classes directory before packaging.

Allowing these strings to make use of the macro expansion from genrules would be really useful, for example to define a binary target in the project which can be used for class processing:
```
java_library(
  name = 'foo',
  postprocess_classes_commands = [
    '$(exe //my/processor:target) arg1 arg2'
  ],
  ...
)
```

In particular this would allow the easy creation of postprocessing helpers for tasks supplied in jars -- like AspectJ's ajc (aspectj-tools.jar) or JiBX binding (jibx-bind.jar) -- which could be trivially defined as java_binary targets, sidestepping $PATH issues.

As a related note, specifically relating to the JiBX binding compiler, the [hardcoded addition of the 'outputDirectory' as an argument](https://github.com/facebook/buck/blob/master/src/com/facebook/buck/jvm/java/BaseCompileToJarStepFactory.java#L120) is also problematic. This particular compiler expects to be run from within that directory, so we have to use a workaround: define a script which pops off the last arg, cds to that directory, and then executes the rest of the command. Similarly to the macro expansion/genrule approach, being able to use `$OUT` as needed would be preferable.

**Comment by marcinkosiba** [comment]
Peter,
  I believe the reason this is undocumented is that it's essentially a hack from a time before genrules:

genrule(
 name = 'post-process',
 cmd = "$(exe //my/processor:target) $(location //my/java_library:jar)",
)

Cheers!
  Martin

**Comment by Zetten** [comment]
That would certainly explain the documentation!

I did think about doing it as a genrule but the exact process wasn't exactly clear - for example the genrule contract states it should be producing a single file/folder as output, and indeed `out` is mandatory. I also couldn't see how a target of this type could be used as a java_library-type for deps/autodeps purposes.

Also, assuming it's possible to update the .classes in-place with another target, how would this work with the java_library's ABI definition? For example if the post-processing changes/adds public stuff it'd be nice to have it available for autodeps.

I couldn't see any easy way to keep the intuitiveness of a single java_library target representing the collection of .java -> .class files (including post-processing), until I started looking at the code and found the java_library parameter. Plus the postprocess_classes_command stuff is executed before the ABI calculation in DefaultJavaLibrary so this kind of naturally fits in.

I might be missing something really easy here - I'm still very much learning the ropes, so any hints in the right direction would be great.

**Comment by marcinkosiba** [comment]
Hi Peter,
  I assumed you'd do this processing on the final java_binary. Using the output as a dep is a bit of a pain as it requires wrapping the output of the genrule in a prebuilt_jar:

java_library(name = 'vanilla', srcs = glob(['*.java]))
genrule(name = 'vanilla_g', cmd="$(exe :processor) $(location :vanilla)", out="vanilla.jar")
prebuilt_jar(name='lib', binary_jar=':vanilla_g') # <-- have other java/android_libraries depend on this, depending on the genrule won't work.

  The ABI stuff works fine with this sort of setup, there will be 2 #abi rules: vanilla#abi and lib#abi. This works because you wouldn't be updating classes in place, you'd be creating an updated copy. Also you'd be getting the .jar file as input, but all you need to do is unzip it to get at the .class files. The output of the genrule should either be a .jar file or a folder with class files which you'd need to convert back into a .jar file.
  Making sure the .class files are jar'd up correctly does seem pretty tedious and I don't see a reason why we couldn't extend the com.facebook.buck.zip.Zip rule to use JarDirectoryStep if the output extension is .jar.

  If you want to add macro support to postprocess_classes instead of going the genrule route, I don't think anyone will stop you, but remember that we make no guarantees as to how long we'll keep this around for and whether .

  You're correct in thinking that this won't work with autodeps. Autodeps is alpha-quality and currently it's not being worked on, but if you want to add a feature to make it understand this kind of post-processing then that would be cool :)

Cheers!
  Martin

**Comment by Zetten** [comment]
Hi Martin,

Thanks for clearing the genrule stuff up - that's put me on the right track now. It's a bit cumbersome, but it definitely makes sense. I'm defining a few target macros to simplify stuff at the module level, but it all makes sense.

I'm wrapping the final prebuilt_jar in a(nother) java_library, so that it can define the tests and exported_deps it needs. This means a bit of wrestling with autodeps, but I guess defining the deps manually is more correct for this sort of tangled situation.

In any case, thanks again. No need for `postprocess_classes_commands` after all!

**Comment by zhihuawensc** [comment]
@Zetten 
Did you figured out how to use aspectj with buck build?
It will be great if you can share your example, thanks a lot.
