### ISSUE TITLE
Expose ANDROID_AAPT_IGNORE property

### ISSUE THREAD

**Issue by MichaelEvans** [facebook/buck#990]
I'm getting an error during `aapt_package` that says that there's a file that's an invalid resource directory - the stack trace says that other files are skipped (like .README.txt) because of (skipping file '.README.txt' due to ANDROID_AAPT_IGNORE pattern '.*')`

Would it be worth exposing this property so that other files that don't match this pattern can be ignored?

**Comment by marcinkosiba** [comment]
The code that does this is pretty old, I think it was an attempt to match the ignore pattern that AAPT applies internally.

Instead of exposing the property, the `android_resource` rules should take the result of running `glob`, just like (almost) all the other rules, rather than taking in a directory as a string and then doing their own special thing. Then the global ignore patterns you can set for the entire project would just work.

To handle aapt having its own ignore logic, I think buck should error out with a descriptive message if the user has globbed anything that aapt would otherwise reject instead of silently ignoring that too.
